// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fence_module.proto

package config

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fence struct {
	// service ports enable lazyload
	WormholePort []string `protobuf:"bytes,1,rep,name=wormholePort,proto3" json:"wormholePort,omitempty"`
	// whether enable ServiceFence auto generating
	// default value is false
	AutoFence bool `protobuf:"varint,2,opt,name=autoFence,proto3" json:"autoFence,omitempty"`
	// the namespace list which enable lazyload
	Namespace []string `protobuf:"bytes,3,rep,name=namespace,proto3" json:"namespace,omitempty"`
	// custom outside dispatch traffic rules
	Dispatches []*Dispatch `protobuf:"bytes,4,rep,name=dispatches,proto3" json:"dispatches,omitempty"`
	// can convert to one or many domain alias rules
	DomainAliases []*DomainAlias `protobuf:"bytes,5,rep,name=domainAliases,proto3" json:"domainAliases,omitempty"`
	// default behavior of create fence or not when autoFence is true
	// default value is false
	DefaultFence bool `protobuf:"varint,6,opt,name=defaultFence,proto3" json:"defaultFence,omitempty"`
	// whether enable http service port auto management
	// default value is false
	AutoPort bool `protobuf:"varint,7,opt,name=autoPort,proto3" json:"autoPort,omitempty"`
	// specify the ns of global-siecar, same as slimeNamespace by default
	ClusterGsNamespace string `protobuf:"bytes,8,opt,name=clusterGsNamespace,proto3" json:"clusterGsNamespace,omitempty"`
	// specify label key and alias to generate sf
	FenceLabelKeyAlias string `protobuf:"bytes,9,opt,name=fenceLabelKeyAlias,proto3" json:"fenceLabelKeyAlias,omitempty"`
	// enableShortDomain, it will generate fqdn and short domain if enabled, otherwise only fqdn is generated in svf and sidecar
	EnableShortDomain bool `protobuf:"varint,10,opt,name=enableShortDomain,proto3" json:"enableShortDomain,omitempty"`
	// deprecated
	// disable ipv4 passthrough
	// mainly deal with compatibility issues with older versions of istio
	// if set true, all ipv4 request will route to global-sidecar
	// default is false, all ipv4 request will route to global-sidecar
	DisableIpv4Passthrough bool `protobuf:"varint,11,opt,name=disableIpv4Passthrough,proto3" json:"disableIpv4Passthrough,omitempty"`
	// passthroughByDefault, if set true, all request will route to PassthroughCluster
	PassthroughByDefault bool `protobuf:"varint,12,opt,name=passthroughByDefault,proto3" json:"passthroughByDefault,omitempty"`
	// grpc and http2 will be supported
	SupportH2 bool `protobuf:"varint,13,opt,name=supportH2,proto3" json:"supportH2,omitempty"`
	// addEnvHeaderViaLua, if set true
	// add header Slime-Orig-Dest Slime-Source-Ns via lua
	AddEnvHeaderViaLua bool `protobuf:"varint,14,opt,name=addEnvHeaderViaLua,proto3" json:"addEnvHeaderViaLua,omitempty"`
	// global sidecar mode, cluster or namespace
	GlobalSidecarMode string `protobuf:"bytes,15,opt,name=globalSidecarMode,proto3" json:"globalSidecarMode,omitempty"`
	// if value is "lazyload", render chart by itself
	Render string `protobuf:"bytes,16,opt,name=render,proto3" json:"render,omitempty"`
	// metric source type, prometheus or accesslog
	MetricSourceType string `protobuf:"bytes,17,opt,name=metricSourceType,proto3" json:"metricSourceType,omitempty"`
	// it will clean up wormholeport if the port is deleted when value is true
	CleanupWormholePort bool `protobuf:"varint,18,opt,name=cleanupWormholePort,proto3" json:"cleanupWormholePort,omitempty"`
	// A list of Kubernetes selectors that specify the set of namespaces that Istio considers when
	// injecting sidecar or refreshing certificates. This can be used to reduce interference between
	// different control planes within the same cluster. If omitted, Istio will use the default
	// behavior of processing all namespaces in the cluster.
	// Elements in the list are disjunctive (OR semantics), i.e. a namespace will be included if it matches any selector.
	// The following example selects any namespace that matches either below:
	// 1. The namespace has both of these labels: `env: prod` and `region: us-east1`
	// 2. The namespace has label `app` equal to `cassandra` or `spark`.
	// ```yaml
	// managementSelectors:
	//   - matchLabels:
	//     env: prod
	//     region: us-east1
	//   - matchExpressions:
	//   - key: app
	//     operator: In
	//     values:
	//   - cassandra
	//   - spark
	//
	// ```
	// Refer to the [kubernetes selector docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors)
	// for additional detail on selector semantics.
	// when autoFence is true, managementSelectors will take effect
	ManagementSelectors []*v1.LabelSelector `protobuf:"bytes,19,rep,name=managementSelectors,proto3" json:"managementSelectors,omitempty"`
	// A list of namespaces that should be excluded or include
	//
	//	when autoFence is true, namespaceList will take effect
	//
	// Types that are valid to be assigned to NamespaceList:
	//
	//	*Fence_BlackNamespaceList
	//	*Fence_WhiteNamespaceList
	NamespaceList isFence_NamespaceList `protobuf_oneof:"namespaceList"`
	// A regular expression in golang regex format (RE2) that can be used to select proxies using a specific version of istio proxy to apply the to_global_sidecar envoyfilter.
	// refer to https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ProxyMatch
	ProxyVersion         string   `protobuf:"bytes,22,opt,name=proxyVersion,proto3" json:"proxyVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fence) Reset()         { *m = Fence{} }
func (m *Fence) String() string { return proto.CompactTextString(m) }
func (*Fence) ProtoMessage()    {}
func (*Fence) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{0}
}
func (m *Fence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fence.Unmarshal(m, b)
}
func (m *Fence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fence.Marshal(b, m, deterministic)
}
func (m *Fence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fence.Merge(m, src)
}
func (m *Fence) XXX_Size() int {
	return xxx_messageInfo_Fence.Size(m)
}
func (m *Fence) XXX_DiscardUnknown() {
	xxx_messageInfo_Fence.DiscardUnknown(m)
}

var xxx_messageInfo_Fence proto.InternalMessageInfo

type isFence_NamespaceList interface {
	isFence_NamespaceList()
}

type Fence_BlackNamespaceList struct {
	BlackNamespaceList string `protobuf:"bytes,20,opt,name=blackNamespaceList,proto3,oneof" json:"blackNamespaceList,omitempty"`
}
type Fence_WhiteNamespaceList struct {
	WhiteNamespaceList string `protobuf:"bytes,21,opt,name=whiteNamespaceList,proto3,oneof" json:"whiteNamespaceList,omitempty"`
}

func (*Fence_BlackNamespaceList) isFence_NamespaceList() {}
func (*Fence_WhiteNamespaceList) isFence_NamespaceList() {}

func (m *Fence) GetNamespaceList() isFence_NamespaceList {
	if m != nil {
		return m.NamespaceList
	}
	return nil
}

func (m *Fence) GetWormholePort() []string {
	if m != nil {
		return m.WormholePort
	}
	return nil
}

func (m *Fence) GetAutoFence() bool {
	if m != nil {
		return m.AutoFence
	}
	return false
}

func (m *Fence) GetNamespace() []string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Fence) GetDispatches() []*Dispatch {
	if m != nil {
		return m.Dispatches
	}
	return nil
}

func (m *Fence) GetDomainAliases() []*DomainAlias {
	if m != nil {
		return m.DomainAliases
	}
	return nil
}

func (m *Fence) GetDefaultFence() bool {
	if m != nil {
		return m.DefaultFence
	}
	return false
}

func (m *Fence) GetAutoPort() bool {
	if m != nil {
		return m.AutoPort
	}
	return false
}

func (m *Fence) GetClusterGsNamespace() string {
	if m != nil {
		return m.ClusterGsNamespace
	}
	return ""
}

func (m *Fence) GetFenceLabelKeyAlias() string {
	if m != nil {
		return m.FenceLabelKeyAlias
	}
	return ""
}

func (m *Fence) GetEnableShortDomain() bool {
	if m != nil {
		return m.EnableShortDomain
	}
	return false
}

func (m *Fence) GetDisableIpv4Passthrough() bool {
	if m != nil {
		return m.DisableIpv4Passthrough
	}
	return false
}

func (m *Fence) GetPassthroughByDefault() bool {
	if m != nil {
		return m.PassthroughByDefault
	}
	return false
}

func (m *Fence) GetSupportH2() bool {
	if m != nil {
		return m.SupportH2
	}
	return false
}

func (m *Fence) GetAddEnvHeaderViaLua() bool {
	if m != nil {
		return m.AddEnvHeaderViaLua
	}
	return false
}

func (m *Fence) GetGlobalSidecarMode() string {
	if m != nil {
		return m.GlobalSidecarMode
	}
	return ""
}

func (m *Fence) GetRender() string {
	if m != nil {
		return m.Render
	}
	return ""
}

func (m *Fence) GetMetricSourceType() string {
	if m != nil {
		return m.MetricSourceType
	}
	return ""
}

func (m *Fence) GetCleanupWormholePort() bool {
	if m != nil {
		return m.CleanupWormholePort
	}
	return false
}

func (m *Fence) GetManagementSelectors() []*v1.LabelSelector {
	if m != nil {
		return m.ManagementSelectors
	}
	return nil
}

func (m *Fence) GetBlackNamespaceList() string {
	if x, ok := m.GetNamespaceList().(*Fence_BlackNamespaceList); ok {
		return x.BlackNamespaceList
	}
	return ""
}

func (m *Fence) GetWhiteNamespaceList() string {
	if x, ok := m.GetNamespaceList().(*Fence_WhiteNamespaceList); ok {
		return x.WhiteNamespaceList
	}
	return ""
}

func (m *Fence) GetProxyVersion() string {
	if m != nil {
		return m.ProxyVersion
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Fence) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Fence_BlackNamespaceList)(nil),
		(*Fence_WhiteNamespaceList)(nil),
	}
}

// The general idea is to assign different default traffic to different targets
// for correct processing by means of domain matching.
type Dispatch struct {
	// dispatch rule name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// domain matching contents
	Domains []string `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	// target cluster
	Cluster string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// google re2 regex expression
	// forward matching request to the cluster
	DomainRegex          string   `protobuf:"bytes,4,opt,name=domainRegex,proto3" json:"domainRegex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dispatch) Reset()         { *m = Dispatch{} }
func (m *Dispatch) String() string { return proto.CompactTextString(m) }
func (*Dispatch) ProtoMessage()    {}
func (*Dispatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{1}
}
func (m *Dispatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dispatch.Unmarshal(m, b)
}
func (m *Dispatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dispatch.Marshal(b, m, deterministic)
}
func (m *Dispatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dispatch.Merge(m, src)
}
func (m *Dispatch) XXX_Size() int {
	return xxx_messageInfo_Dispatch.Size(m)
}
func (m *Dispatch) XXX_DiscardUnknown() {
	xxx_messageInfo_Dispatch.DiscardUnknown(m)
}

var xxx_messageInfo_Dispatch proto.InternalMessageInfo

func (m *Dispatch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dispatch) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Dispatch) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Dispatch) GetDomainRegex() string {
	if m != nil {
		return m.DomainRegex
	}
	return ""
}

// DomainAlias regexp expression, which is alias for target domain
// default value is empty
// example:
// domainAliases:
//   - pattern: (?P<service>[^\.]+)\.(?P<namespace>[^\.]+)\.svc\.cluster\.local$
//     template:
//   - $namespace.$service.service.mailsaas
type DomainAlias struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Templates            []string `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainAlias) Reset()         { *m = DomainAlias{} }
func (m *DomainAlias) String() string { return proto.CompactTextString(m) }
func (*DomainAlias) ProtoMessage()    {}
func (*DomainAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{2}
}
func (m *DomainAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainAlias.Unmarshal(m, b)
}
func (m *DomainAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainAlias.Marshal(b, m, deterministic)
}
func (m *DomainAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainAlias.Merge(m, src)
}
func (m *DomainAlias) XXX_Size() int {
	return xxx_messageInfo_DomainAlias.Size(m)
}
func (m *DomainAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainAlias.DiscardUnknown(m)
}

var xxx_messageInfo_DomainAlias proto.InternalMessageInfo

func (m *DomainAlias) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *DomainAlias) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

func init() {
	proto.RegisterType((*Fence)(nil), "slime.microservice.lazyload.config.Fence")
	proto.RegisterType((*Dispatch)(nil), "slime.microservice.lazyload.config.Dispatch")
	proto.RegisterType((*DomainAlias)(nil), "slime.microservice.lazyload.config.DomainAlias")
}

func init() { proto.RegisterFile("fence_module.proto", fileDescriptor_8eebc4b237a55c9b) }

var fileDescriptor_8eebc4b237a55c9b = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0xeb, 0x3e, 0x5a, 0x77, 0x63, 0x9b, 0x37, 0x26, 0x6b, 0xe2, 0xa1, 0xea, 0x53, 0x35,
	0x4d, 0xc9, 0xbe, 0x84, 0x78, 0x65, 0xda, 0x60, 0x88, 0x82, 0xa6, 0x14, 0x86, 0xc4, 0x0b, 0x72,
	0x93, 0xbb, 0xc4, 0xaa, 0x63, 0x5b, 0xb6, 0xd3, 0xad, 0xfc, 0x32, 0x7e, 0x1e, 0xb2, 0xd3, 0xf4,
	0x43, 0x2d, 0x82, 0xb7, 0xdc, 0x73, 0xee, 0xb9, 0xf1, 0xb1, 0xef, 0xbd, 0x08, 0x3f, 0x82, 0x88,
	0xe1, 0x67, 0x2e, 0x93, 0x82, 0x43, 0xa0, 0xb4, 0xb4, 0x12, 0x77, 0x0c, 0x67, 0x39, 0x04, 0x39,
	0x8b, 0xb5, 0x34, 0xa0, 0x47, 0x2c, 0x86, 0x80, 0xd3, 0x5f, 0x63, 0x2e, 0x69, 0x12, 0xc4, 0x52,
	0x3c, 0xb2, 0xf4, 0xf8, 0x6a, 0xf8, 0xd6, 0x04, 0x4c, 0x86, 0x54, 0xb1, 0x9c, 0xc6, 0x19, 0x13,
	0xa0, 0xc7, 0xa1, 0x1a, 0xa6, 0x0e, 0x30, 0x61, 0x0e, 0x96, 0x86, 0xa3, 0xf3, 0x30, 0x05, 0x01,
	0x9a, 0x5a, 0x48, 0xca, 0xca, 0x9d, 0xdf, 0x0d, 0xb4, 0xf1, 0xde, 0xfd, 0x10, 0x77, 0xd0, 0xf6,
	0x93, 0xd4, 0x79, 0x26, 0x39, 0xdc, 0x4b, 0x6d, 0x49, 0xad, 0x5d, 0xef, 0x36, 0xa3, 0x05, 0x0c,
	0xbf, 0x46, 0x4d, 0x5a, 0x58, 0xe9, 0x05, 0x64, 0xad, 0x5d, 0xeb, 0x36, 0xa2, 0x19, 0xe0, 0x58,
	0x41, 0x73, 0x30, 0x8a, 0xc6, 0x40, 0xea, 0x5e, 0x3e, 0x03, 0x70, 0x0f, 0xa1, 0x84, 0x19, 0x45,
	0x6d, 0x9c, 0x81, 0x21, 0xeb, 0xed, 0x7a, 0xb7, 0x75, 0x71, 0x1a, 0xfc, 0xdb, 0x58, 0x70, 0x33,
	0x51, 0x45, 0x73, 0x7a, 0xfc, 0x0d, 0xed, 0x24, 0x32, 0xa7, 0x4c, 0xbc, 0xe3, 0x8c, 0x1a, 0x30,
	0x64, 0xc3, 0x17, 0x0c, 0xff, 0xab, 0xe0, 0x4c, 0x18, 0x2d, 0x56, 0x71, 0x97, 0x90, 0xc0, 0x23,
	0x2d, 0xb8, 0x2d, 0x3d, 0x6e, 0x7a, 0x8f, 0x0b, 0x18, 0x3e, 0x46, 0x0d, 0xe7, 0xd9, 0x5f, 0xd2,
	0x96, 0xe7, 0xa7, 0x31, 0x0e, 0x10, 0x8e, 0x79, 0x61, 0x2c, 0xe8, 0x0f, 0xe6, 0xcb, 0xf4, 0x2e,
	0x1a, 0xed, 0x5a, 0xb7, 0x19, 0xad, 0x60, 0x5c, 0xbe, 0x7f, 0xee, 0x1e, 0x1d, 0x00, 0xff, 0x04,
	0x63, 0x7f, 0x0e, 0xd2, 0x2c, 0xf3, 0x97, 0x19, 0x7c, 0x8a, 0xf6, 0x41, 0xd0, 0x01, 0x87, 0x7e,
	0x26, 0xb5, 0x2d, 0x8d, 0x10, 0xe4, 0x0f, 0xb1, 0x4c, 0xe0, 0x37, 0xe8, 0x28, 0x61, 0xc6, 0xa1,
	0x1f, 0xd5, 0xe8, 0xea, 0x9e, 0x1a, 0x63, 0x33, 0x2d, 0x8b, 0x34, 0x23, 0x2d, 0x2f, 0xf9, 0x0b,
	0x8b, 0x2f, 0xd0, 0xa1, 0x9a, 0x85, 0xd7, 0xe3, 0x9b, 0xd2, 0x3e, 0xd9, 0xf6, 0xaa, 0x95, 0x9c,
	0x7b, 0x7c, 0x53, 0x28, 0x25, 0xb5, 0xbd, 0xbb, 0x20, 0x3b, 0x65, 0x6b, 0x4c, 0x01, 0xe7, 0x93,
	0x26, 0xc9, 0xad, 0x18, 0xdd, 0x01, 0x4d, 0x40, 0x3f, 0x30, 0xda, 0x2b, 0x28, 0x79, 0xe9, 0xd3,
	0x56, 0x30, 0xce, 0x67, 0xca, 0xe5, 0x80, 0xf2, 0x3e, 0x4b, 0x20, 0xa6, 0xfa, 0xb3, 0x4c, 0x80,
	0xec, 0xfa, 0x6b, 0x59, 0x26, 0xf0, 0x11, 0xda, 0xd4, 0x20, 0x12, 0xd0, 0x64, 0xcf, 0xa7, 0x4c,
	0x22, 0x7c, 0x82, 0xf6, 0x72, 0xb0, 0x9a, 0xc5, 0x7d, 0x59, 0xe8, 0x18, 0xbe, 0x8e, 0x15, 0x90,
	0x7d, 0x9f, 0xb1, 0x84, 0xe3, 0x33, 0x74, 0x10, 0x73, 0xa0, 0xa2, 0x50, 0xdf, 0xe7, 0xa7, 0x00,
	0xfb, 0x23, 0xae, 0xa2, 0x30, 0xa0, 0x83, 0x9c, 0x0a, 0x9a, 0x42, 0x0e, 0xc2, 0xf6, 0x81, 0x43,
	0x6c, 0xa5, 0x36, 0xe4, 0xc0, 0x37, 0xe2, 0x65, 0x50, 0x8e, 0x63, 0x30, 0x3f, 0x8e, 0x81, 0x1a,
	0xa6, 0x0e, 0x30, 0x81, 0x1b, 0xc7, 0x60, 0x74, 0x1e, 0xf8, 0xd7, 0xad, 0xb4, 0xd1, 0xaa, 0x7a,
	0xf8, 0x0c, 0xe1, 0x01, 0xa7, 0xf1, 0x70, 0xda, 0x34, 0x3d, 0x66, 0x2c, 0x39, 0x74, 0x36, 0xee,
	0x5e, 0x44, 0x2b, 0x38, 0xa7, 0x78, 0xca, 0x98, 0x85, 0x45, 0xc5, 0xab, 0x4a, 0xb1, 0xcc, 0xb9,
	0xb6, 0x57, 0x5a, 0x3e, 0x8f, 0x1f, 0x40, 0x1b, 0x26, 0x05, 0x39, 0xf2, 0x97, 0xb4, 0x80, 0x5d,
	0xef, 0xa2, 0x1d, 0x31, 0x2f, 0xea, 0x58, 0xd4, 0xa8, 0x46, 0x13, 0x63, 0xb4, 0xee, 0x48, 0x52,
	0xf3, 0x42, 0xff, 0x8d, 0x09, 0xda, 0x2a, 0x87, 0xcb, 0x90, 0x35, 0xbf, 0x0c, 0xaa, 0xd0, 0x31,
	0x93, 0x59, 0x20, 0x75, 0x2f, 0xa8, 0x42, 0xdc, 0x46, 0xad, 0x32, 0x29, 0x82, 0x14, 0x9e, 0xc9,
	0xba, 0x67, 0xe7, 0xa1, 0xce, 0x2d, 0x6a, 0xcd, 0xcd, 0xaf, 0x2b, 0xa5, 0xa8, 0xb5, 0xa0, 0xc5,
	0xe4, 0xdf, 0x55, 0xe8, 0x1a, 0xd2, 0x42, 0xae, 0x38, 0xb5, 0x50, 0x1d, 0x60, 0x06, 0x5c, 0x9f,
	0xfe, 0x38, 0x29, 0x37, 0x05, 0x93, 0xa1, 0xff, 0x08, 0xcb, 0x85, 0x6b, 0xc2, 0x6a, 0x5b, 0xb8,
	0xbd, 0x19, 0x96, 0x1b, 0x63, 0xb0, 0xe9, 0x97, 0xe5, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x41, 0xa3, 0x15, 0x9c, 0x05, 0x00, 0x00,
}
