// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package config

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Limiter
func (this *Limiter) MarshalJSON() ([]byte, error) {
	str, err := LimiterModuleMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Limiter
func (this *Limiter) UnmarshalJSON(b []byte) error {
	return LimiterModuleUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RlsConfigMap
func (this *RlsConfigMap) MarshalJSON() ([]byte, error) {
	str, err := LimiterModuleMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RlsConfigMap
func (this *RlsConfigMap) UnmarshalJSON(b []byte) error {
	return LimiterModuleUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitService
func (this *RateLimitService) MarshalJSON() ([]byte, error) {
	str, err := LimiterModuleMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitService
func (this *RateLimitService) UnmarshalJSON(b []byte) error {
	return LimiterModuleUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	LimiterModuleMarshaler   = &jsonpb.Marshaler{}
	LimiterModuleUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
