apiVersion: microservice.slime.io/v1alpha2
kind: SmartLimiter
metadata:
  name: productpage
  namespace: default
spec:
  sets:
    _base:
      descriptor:
        - action:
            fill_interval:
              seconds: 60
            quota: "2"
            strategy: "single"
          condition: "true"
          target:
            port: 9080