apiVersion: v1
kind: ConfigMap
metadata:
  name: slime-rate-limit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: slime  

## redis 服务，依赖 configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rate-limit-redis
  name: rate-limit-redis
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limit-redis
  template:
    metadata:
      labels:
        app: rate-limit-redis
    spec:
      containers:
      - env:
        - name: MASTER
          value: "true"
        image: redis:5
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rate-limit-redis
  name: rate-limit-redis
  namespace: istio-system
spec:
  ports:
  - name: one-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: rate-limit-redis
  type: ClusterIP


# rls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rate-limit
  name: rate-limit
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limit
  template:
    metadata:
      labels:
        app: rate-limit
    spec:
      containers:
      - command:
        - /bin/ratelimit
        env:
        - name: GRPC_PORT
          value: "18081"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: debug
        - name: USE_STATSD
          value: "false"  
        - name: REDIS_URL
          value: rate-limit-redis.istio-system:6379
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        image: slimeio/ratelimit:v1.0
        imagePullPolicy: IfNotPresent
        name: rate-limit
        volumeMounts:
        - mountPath: /data/ratelimit/config
          name: slime-rate-limit-config
      volumes:
      - configMap:
          defaultMode: 420
          name: slime-rate-limit-config
        name: slime-rate-limit-config  

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rate-limit
    release: istio-system-rls
  name: rate-limit
  namespace: istio-system
spec:
  ports:
  - name: grpc
    port: 18081
    protocol: TCP
    targetPort: 18081
  - name: config-grpc
    port: 16071
    protocol: TCP
    targetPort: 6071
  selector:
    app: rate-limit
  type: ClusterIP        
