# permissions for end users to view smartlimiters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smartlimiter-viewer-role
rules:
- apiGroups:
  - microservice.slime.io
  resources:
  - smartlimiters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microservice.slime.io
  resources:
  - smartlimiters/status
  verbs:
  - get
