# permissions for end users to edit smartlimiters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smartlimiter-editor-role
rules:
- apiGroups:
  - microservice.slime.io
  resources:
  - smartlimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microservice.slime.io
  resources:
  - smartlimiters/status
  verbs:
  - get
