// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example_module.proto

package config

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using Example within kubernetes types, where deepcopy-gen is used.
func (in *Example) DeepCopyInto(out *Example) {
	p := proto.Clone(in).(*Example)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Example. Required by controller-gen.
func (in *Example) DeepCopy() *Example {
	if in == nil {
		return nil
	}
	out := new(Example)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Example. Required by controller-gen.
func (in *Example) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
