apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smartlimiters.microservice.slime.io
spec:
  group: microservice.slime.io
  names:
    kind: SmartLimiter
    listKind: SmartLimiterList
    plural: smartlimiters
    singular: smartlimiter
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
    - name: v1alpha2
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: envoyplugins.microservice.slime.io
spec:
  group: microservice.slime.io
  names:
    shortNames:
      - evp
    kind: EnvoyPlugin
    listKind: EnvoyPluginList
    plural: envoyplugins
    singular: envoyplugin
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pluginmanagers.microservice.slime.io
spec:
  group: microservice.slime.io
  names:
    shortNames:
      - plm
    kind: PluginManager
    listKind: PluginManagerList
    plural: pluginmanagers
    singular: pluginmanager
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true