// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: limiter_module.proto

package v1alpha2

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Limiter_RateLimitBackend int32

const (
	Limiter_netEaseLocalFlowControl Limiter_RateLimitBackend = 0
	Limiter_envoyLocalRateLimit     Limiter_RateLimitBackend = 1
)

var Limiter_RateLimitBackend_name = map[int32]string{
	0: "netEaseLocalFlowControl",
	1: "envoyLocalRateLimit",
}

var Limiter_RateLimitBackend_value = map[string]int32{
	"netEaseLocalFlowControl": 0,
	"envoyLocalRateLimit":     1,
}

func (x Limiter_RateLimitBackend) String() string {
	return proto.EnumName(Limiter_RateLimitBackend_name, int32(x))
}

func (Limiter_RateLimitBackend) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4827d40f7d98bcf0, []int{0, 0}
}

type Limiter struct {
	Backend Limiter_RateLimitBackend `protobuf:"varint,3,opt,name=backend,proto3,enum=slime.microservice.limiter.v1alpha2.Limiter_RateLimitBackend" json:"backend,omitempty"`
	Refresh *time.Duration           `protobuf:"bytes,4,opt,name=refresh,proto3,stdduration" json:"refresh,omitempty"`
	// it will disable GlobalRateLimit
	DisableGlobalRateLimit bool `protobuf:"varint,5,opt,name=disableGlobalRateLimit,proto3" json:"disableGlobalRateLimit,omitempty"`
	// it will disable use promql
	DisableAdaptive    bool `protobuf:"varint,6,opt,name=disableAdaptive,proto3" json:"disableAdaptive,omitempty"`
	EnableServiceEntry bool `protobuf:"varint,7,opt,name=enableServiceEntry,proto3" json:"enableServiceEntry,omitempty"`
	// it will not generate envoy.filters.http.local_ratelimit insert before http.router when true
	DisableInsertLocalRateLimit bool `protobuf:"varint,8,opt,name=disableInsertLocalRateLimit,proto3" json:"disableInsertLocalRateLimit,omitempty"`
	// it will not generate envoy.filters.http.ratelimit insert before http.router when true
	DisableInsertGlobalRateLimit bool `protobuf:"varint,9,opt,name=disableInsertGlobalRateLimit,proto3" json:"disableInsertGlobalRateLimit,omitempty"`
	// specify the rls namespaces
	RlsConfigMap *RlsConfigMap `protobuf:"bytes,10,opt,name=rlsConfigMap,proto3" json:"rlsConfigMap,omitempty"`
	// specify domain, it is useful in global ratelimiter
	Domain string `protobuf:"bytes,11,opt,name=domain,proto3" json:"domain,omitempty"`
	// specify rls server address, if disableInsertGlobalRateLimit if false
	Rls                  *RateLimitService `protobuf:"bytes,12,opt,name=rls,proto3" json:"rls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Limiter) Reset()         { *m = Limiter{} }
func (m *Limiter) String() string { return proto.CompactTextString(m) }
func (*Limiter) ProtoMessage()    {}
func (*Limiter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4827d40f7d98bcf0, []int{0}
}
func (m *Limiter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limiter.Unmarshal(m, b)
}
func (m *Limiter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limiter.Marshal(b, m, deterministic)
}
func (m *Limiter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limiter.Merge(m, src)
}
func (m *Limiter) XXX_Size() int {
	return xxx_messageInfo_Limiter.Size(m)
}
func (m *Limiter) XXX_DiscardUnknown() {
	xxx_messageInfo_Limiter.DiscardUnknown(m)
}

var xxx_messageInfo_Limiter proto.InternalMessageInfo

func (m *Limiter) GetBackend() Limiter_RateLimitBackend {
	if m != nil {
		return m.Backend
	}
	return Limiter_netEaseLocalFlowControl
}

func (m *Limiter) GetRefresh() *time.Duration {
	if m != nil {
		return m.Refresh
	}
	return nil
}

func (m *Limiter) GetDisableGlobalRateLimit() bool {
	if m != nil {
		return m.DisableGlobalRateLimit
	}
	return false
}

func (m *Limiter) GetDisableAdaptive() bool {
	if m != nil {
		return m.DisableAdaptive
	}
	return false
}

func (m *Limiter) GetEnableServiceEntry() bool {
	if m != nil {
		return m.EnableServiceEntry
	}
	return false
}

func (m *Limiter) GetDisableInsertLocalRateLimit() bool {
	if m != nil {
		return m.DisableInsertLocalRateLimit
	}
	return false
}

func (m *Limiter) GetDisableInsertGlobalRateLimit() bool {
	if m != nil {
		return m.DisableInsertGlobalRateLimit
	}
	return false
}

func (m *Limiter) GetRlsConfigMap() *RlsConfigMap {
	if m != nil {
		return m.RlsConfigMap
	}
	return nil
}

func (m *Limiter) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Limiter) GetRls() *RateLimitService {
	if m != nil {
		return m.Rls
	}
	return nil
}

// configmap will mount to RateLimitService '/data/ratelimit/config'
type RlsConfigMap struct {
	// configmap name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// configmap namespace
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RlsConfigMap) Reset()         { *m = RlsConfigMap{} }
func (m *RlsConfigMap) String() string { return proto.CompactTextString(m) }
func (*RlsConfigMap) ProtoMessage()    {}
func (*RlsConfigMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_4827d40f7d98bcf0, []int{1}
}
func (m *RlsConfigMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RlsConfigMap.Unmarshal(m, b)
}
func (m *RlsConfigMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RlsConfigMap.Marshal(b, m, deterministic)
}
func (m *RlsConfigMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RlsConfigMap.Merge(m, src)
}
func (m *RlsConfigMap) XXX_Size() int {
	return xxx_messageInfo_RlsConfigMap.Size(m)
}
func (m *RlsConfigMap) XXX_DiscardUnknown() {
	xxx_messageInfo_RlsConfigMap.DiscardUnknown(m)
}

var xxx_messageInfo_RlsConfigMap proto.InternalMessageInfo

func (m *RlsConfigMap) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RlsConfigMap) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type RateLimitService struct {
	// rate-limit.gateway-system.svc.cluster.local
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// service port
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateLimitService) Reset()         { *m = RateLimitService{} }
func (m *RateLimitService) String() string { return proto.CompactTextString(m) }
func (*RateLimitService) ProtoMessage()    {}
func (*RateLimitService) Descriptor() ([]byte, []int) {
	return fileDescriptor_4827d40f7d98bcf0, []int{2}
}
func (m *RateLimitService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimitService.Unmarshal(m, b)
}
func (m *RateLimitService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimitService.Marshal(b, m, deterministic)
}
func (m *RateLimitService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimitService.Merge(m, src)
}
func (m *RateLimitService) XXX_Size() int {
	return xxx_messageInfo_RateLimitService.Size(m)
}
func (m *RateLimitService) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimitService.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimitService proto.InternalMessageInfo

func (m *RateLimitService) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RateLimitService) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterEnum("slime.microservice.limiter.v1alpha2.Limiter_RateLimitBackend", Limiter_RateLimitBackend_name, Limiter_RateLimitBackend_value)
	proto.RegisterType((*Limiter)(nil), "slime.microservice.limiter.v1alpha2.Limiter")
	proto.RegisterType((*RlsConfigMap)(nil), "slime.microservice.limiter.v1alpha2.RlsConfigMap")
	proto.RegisterType((*RateLimitService)(nil), "slime.microservice.limiter.v1alpha2.RateLimitService")
}

func init() { proto.RegisterFile("limiter_module.proto", fileDescriptor_4827d40f7d98bcf0) }

var fileDescriptor_4827d40f7d98bcf0 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x76, 0x6d, 0x93, 0x34, 0xa7, 0x41, 0xc3, 0x28, 0xed, 0xd8, 0x16, 0x0d, 0xf1, 0x66, 0x41,
	0x3a, 0x4b, 0x23, 0x0a, 0x5e, 0x08, 0x31, 0xb5, 0x56, 0xa1, 0xde, 0xac, 0x88, 0xe0, 0x8d, 0xcc,
	0xee, 0x4e, 0x36, 0x83, 0xb3, 0x73, 0x96, 0xd9, 0x49, 0xa4, 0x6f, 0xe2, 0x9b, 0xf8, 0x38, 0xbe,
	0x8a, 0x64, 0x76, 0xd6, 0x26, 0x41, 0x4b, 0xae, 0x72, 0x7e, 0xbe, 0xf3, 0x9d, 0xef, 0x7c, 0x99,
	0x85, 0x87, 0x4a, 0x16, 0xd2, 0x0a, 0xf3, 0xad, 0xc0, 0x6c, 0xae, 0x04, 0x2b, 0x0d, 0x5a, 0x24,
	0x4f, 0x2b, 0x25, 0x0b, 0xc1, 0x0a, 0x99, 0x1a, 0xac, 0x84, 0x59, 0xc8, 0x54, 0x30, 0x0f, 0x64,
	0x8b, 0x33, 0xae, 0xca, 0x19, 0x1f, 0x1d, 0x9d, 0xe6, 0xd2, 0xce, 0xe6, 0x09, 0x4b, 0xb1, 0x88,
	0x72, 0xcc, 0x31, 0x72, 0xb3, 0xc9, 0x7c, 0xea, 0x32, 0x97, 0xb8, 0xa8, 0xe6, 0x3c, 0x7a, 0x9c,
	0x23, 0xe6, 0x4a, 0xdc, 0xa0, 0xb2, 0xb9, 0xe1, 0x56, 0xa2, 0xae, 0xfb, 0xc3, 0x5f, 0x2d, 0xe8,
	0x5c, 0xd5, 0x3b, 0xc8, 0x17, 0xe8, 0x24, 0x3c, 0xfd, 0x2e, 0x74, 0x46, 0x77, 0x06, 0x41, 0x78,
	0x6f, 0xf4, 0x9a, 0x6d, 0xa1, 0x88, 0xf9, 0x71, 0x16, 0x73, 0x2b, 0x5c, 0x3c, 0xa9, 0x49, 0xe2,
	0x86, 0x8d, 0xbc, 0x82, 0x8e, 0x11, 0x53, 0x23, 0xaa, 0x19, 0xdd, 0x1d, 0x04, 0xe1, 0xfe, 0xe8,
	0x11, 0xab, 0x65, 0xb1, 0x46, 0x16, 0x7b, 0xeb, 0x65, 0x4d, 0x76, 0x7f, 0xfe, 0x7e, 0x12, 0xc4,
	0x0d, 0x9e, 0xbc, 0x84, 0x83, 0x4c, 0x56, 0x3c, 0x51, 0xe2, 0x52, 0x61, 0xc2, 0xd5, 0xdf, 0x25,
	0xb4, 0x35, 0x08, 0xc2, 0xbd, 0xf8, 0x3f, 0x5d, 0x12, 0xc2, 0x7d, 0xdf, 0x79, 0x93, 0xf1, 0xd2,
	0xca, 0x85, 0xa0, 0x6d, 0x37, 0xb0, 0x59, 0x26, 0x0c, 0x88, 0xd0, 0xcb, 0xca, 0xa7, 0xfa, 0xc0,
	0x0b, 0x6d, 0xcd, 0x35, 0xed, 0x38, 0xf0, 0x3f, 0x3a, 0x64, 0x0c, 0xc7, 0x9e, 0xe2, 0x83, 0xae,
	0x84, 0xb1, 0x57, 0x98, 0xae, 0xca, 0xda, 0x73, 0x83, 0xb7, 0x41, 0xc8, 0x04, 0x4e, 0xd6, 0xda,
	0x9b, 0x97, 0x75, 0x1d, 0xc5, 0xad, 0x18, 0xf2, 0x19, 0x7a, 0x46, 0x55, 0xe7, 0xa8, 0xa7, 0x32,
	0xff, 0xc8, 0x4b, 0x0a, 0xce, 0xd7, 0xb3, 0xad, 0xfe, 0xb0, 0x78, 0x65, 0x30, 0x5e, 0xa3, 0x21,
	0x07, 0xd0, 0xce, 0xb0, 0xe0, 0x52, 0xd3, 0xfd, 0x41, 0x10, 0x76, 0x63, 0x9f, 0x91, 0x4b, 0xd8,
	0x31, 0xaa, 0xa2, 0x3d, 0xb7, 0xe5, 0xc5, 0x76, 0x5b, 0x1a, 0xad, 0xde, 0xbd, 0x78, 0xc9, 0x30,
	0x7c, 0x0f, 0xfd, 0xcd, 0x77, 0x42, 0x8e, 0xe1, 0x50, 0x0b, 0x7b, 0xc1, 0x2b, 0xe1, 0x8c, 0x7a,
	0xa7, 0xf0, 0xc7, 0x39, 0x6a, 0x6b, 0x50, 0xf5, 0xef, 0x90, 0x43, 0x78, 0x20, 0xf4, 0x02, 0xaf,
	0xd7, 0x3d, 0xec, 0x07, 0xc3, 0x31, 0xf4, 0x56, 0x0f, 0x21, 0x04, 0x76, 0x35, 0x2f, 0x04, 0x0d,
	0x9c, 0x70, 0x17, 0x93, 0x13, 0xe8, 0x2e, 0x7f, 0xab, 0x92, 0xa7, 0x82, 0xde, 0x75, 0x8d, 0x9b,
	0xc2, 0x70, 0xbc, 0xa2, 0xc5, 0x8b, 0x24, 0x14, 0x3a, 0xfe, 0x22, 0x4f, 0xd4, 0xa4, 0x4b, 0xfe,
	0x12, 0x8d, 0x75, 0x34, 0xad, 0xd8, 0xc5, 0x93, 0xd3, 0xaf, 0xcf, 0x6a, 0x2b, 0x24, 0x46, 0x2e,
	0x88, 0xea, 0x0f, 0xba, 0x8a, 0xbc, 0x1d, 0x11, 0x2f, 0x65, 0xd4, 0x58, 0x92, 0xb4, 0xdd, 0x73,
	0x7f, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x67, 0xb3, 0x98, 0xa6, 0xff, 0x03, 0x00, 0x00,
}
