---
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: lazyload-bundle
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: registry.cn-hangzhou.aliyuncs.com/slimeio/slime-bundle-example-all
    tag: v0.3.11_linux_amd64-dirty_  # should be replaced with actual repo/tag
  module:
    - name: lazyload-bundle
      enable: true
      bundle:
        modules:
          - name: lazyload-v1
            kind: lazyload
          - name: lazyload-v2
            kind: lazyload
      global:
        log:
          logLevel: debug
    - name: lazyload-v1
      kind: lazyload
      enable: true
      mode: BundleItem
      general:
        wormholePort: # replace to your application svc ports
          - "9080"
        namespace:
          - default
      global:
        istioRev: v1
        misc:
          globalSidecarMode: namespace
          metricSourceType: accesslog
    - name: lazyload-v2
      kind: lazyload
      enable: true
      mode: BundleItem
      general:
        wormholePort: # replace to your application svc ports
          - "80"
        namespace:
          - test
      global:
        istioRev: v2
        strictRev: true
        misc:
          globalSidecarMode: namespace
          metricSourceType: accesslog
  component:  # for lazyload
    globalSidecar:
      enable: true
      sidecarInject:
        enable: true
        mode: pod
        labels: # optional, used for sidecarInject.mode = pod
          sidecar.istio.io/inject: "true"
          # istio.io/rev: canary # use control plane revisions
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 400m
          memory: 400Mi
      image:
        repository: registry.cn-hangzhou.aliyuncs.com/slimeio/slime-global-sidecar
        tag: v0.2.0-1b93bf7
