apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: smartlimiter
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.pkg.github.com/slime-io/slime/slime:v0.1.0
    tag: v0.1.0
  imagePullSecrets:
    - name: slime-secret
  module:
    - limiter:
        enable: true
        backend: 1
      name: limiter