apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: smartlimiter
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.io/hazard1905/slime
    tag: v0.1.1
  module:
    - limiter:
        enable: true
        backend: 1
      name: limiter