apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicefences.microservice.slime.io
spec:
  group: microservice.slime.io
  names:
    shortNames:
      - svf
    kind: ServiceFence
    listKind: ServiceFenceList
    plural: servicefences
    singular: servicefence
  scope: Namespaced
  subresources:
    status: { }
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: slimeboots.config.netease.com
spec:
  group: config.netease.com
  names:
    kind: SlimeBoot
    listKind: SlimeBootList
    plural: slimeboots
    singular: slimeboot
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
    - name: v1alpha1
      served: true
      storage: true

