apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: lazyload
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.io/slimeio/slime-lazyload
    tag: v0.2.6-d808438
  module:
    - fence:
        enable: true
        wormholePort:
          - "9080"
      name: slime-fence
      global:
        misc:
          global-sidecar-mode: cluster
      metric:
        prometheus:
          address: http://prometheus.istio-system:9090
          handlers:
            destination:
              query: |
                sum(istio_requests_total{source_app="$source_app",reporter="destination"})by(destination_service)
              type: Group
  component:
    globalSidecar:
      enable: true
      type: cluster
    pilot:
      enable: true
      image:
        repository: docker.io/slimeio/pilot
        tag: globalPilot-7.0-v0.0.3-833f1bd5c1