apiVersion: apps/v1
kind: Deployment
metadata:
  name: slime-boot
  namespace: mesh-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slime-boot
  template:
    metadata:
      labels:
        name: slime-boot
    spec:
      serviceAccountName: slime-boot
      containers:
        - name: slime-boot
          # Replace this with the built image name
          image: docker.io/slimeio/slime-boot:v0.5.0_linux_amd64
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "slime-boot"
