// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/microservice/v1alpha1/smart_limiter.proto

package v1alpha1

import (
	fmt "fmt"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action struct {
	Quota                string          `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`
	FillInterval         *types.Duration `protobuf:"bytes,2,opt,name=fill_interval,json=fillInterval,proto3" json:"fill_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetQuota() string {
	if m != nil {
		return m.Quota
	}
	return ""
}

func (m *Action) GetFillInterval() *types.Duration {
	if m != nil {
		return m.FillInterval
	}
	return nil
}

type ActionStatus struct {
	Quota                uint32          `protobuf:"varint,1,opt,name=quota,proto3" json:"quota,omitempty"`
	FillInterval         *types.Duration `protobuf:"bytes,2,opt,name=fill_interval,json=fillInterval,proto3" json:"fill_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionStatus) Reset()         { *m = ActionStatus{} }
func (m *ActionStatus) String() string { return proto.CompactTextString(m) }
func (*ActionStatus) ProtoMessage()    {}
func (*ActionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{1}
}

func (m *ActionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionStatus.Unmarshal(m, b)
}
func (m *ActionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionStatus.Marshal(b, m, deterministic)
}
func (m *ActionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionStatus.Merge(m, src)
}
func (m *ActionStatus) XXX_Size() int {
	return xxx_messageInfo_ActionStatus.Size(m)
}
func (m *ActionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ActionStatus proto.InternalMessageInfo

func (m *ActionStatus) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *ActionStatus) GetFillInterval() *types.Duration {
	if m != nil {
		return m.FillInterval
	}
	return nil
}

type SmartLimitDescriptor struct {
	Condition            string           `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Action               *Action          `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Match                []*HeaderMatcher `protobuf:"bytes,4,rep,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SmartLimitDescriptor) Reset()         { *m = SmartLimitDescriptor{} }
func (m *SmartLimitDescriptor) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptor) ProtoMessage()    {}
func (*SmartLimitDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{2}
}

func (m *SmartLimitDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptor.Unmarshal(m, b)
}
func (m *SmartLimitDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptor.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptor.Merge(m, src)
}
func (m *SmartLimitDescriptor) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptor.Size(m)
}
func (m *SmartLimitDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptor proto.InternalMessageInfo

func (m *SmartLimitDescriptor) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *SmartLimitDescriptor) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *SmartLimitDescriptor) GetMatch() []*HeaderMatcher {
	if m != nil {
		return m.Match
	}
	return nil
}

type SmartLimitDescriptorStatus struct {
	Condition            string           `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Action               *ActionStatus    `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Match                []*HeaderMatcher `protobuf:"bytes,4,rep,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SmartLimitDescriptorStatus) Reset()         { *m = SmartLimitDescriptorStatus{} }
func (m *SmartLimitDescriptorStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptorStatus) ProtoMessage()    {}
func (*SmartLimitDescriptorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{3}
}

func (m *SmartLimitDescriptorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptorStatus.Unmarshal(m, b)
}
func (m *SmartLimitDescriptorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptorStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptorStatus.Merge(m, src)
}
func (m *SmartLimitDescriptorStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptorStatus.Size(m)
}
func (m *SmartLimitDescriptorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptorStatus proto.InternalMessageInfo

func (m *SmartLimitDescriptorStatus) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *SmartLimitDescriptorStatus) GetAction() *ActionStatus {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *SmartLimitDescriptorStatus) GetMatch() []*HeaderMatcher {
	if m != nil {
		return m.Match
	}
	return nil
}

type SmartLimiterSpec struct {
	Domain               string                  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Descriptors          []*SmartLimitDescriptor `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SmartLimiterSpec) Reset()         { *m = SmartLimiterSpec{} }
func (m *SmartLimiterSpec) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterSpec) ProtoMessage()    {}
func (*SmartLimiterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{4}
}

func (m *SmartLimiterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterSpec.Unmarshal(m, b)
}
func (m *SmartLimiterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterSpec.Marshal(b, m, deterministic)
}
func (m *SmartLimiterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterSpec.Merge(m, src)
}
func (m *SmartLimiterSpec) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterSpec.Size(m)
}
func (m *SmartLimiterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterSpec proto.InternalMessageInfo

func (m *SmartLimiterSpec) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SmartLimiterSpec) GetDescriptors() []*SmartLimitDescriptor {
	if m != nil {
		return m.Descriptors
	}
	return nil
}

type SmartLimiterStatus struct {
	RatelimitStatus      []*SmartLimitDescriptor           `protobuf:"bytes,1,rep,name=ratelimitStatus,proto3" json:"ratelimitStatus,omitempty"`
	EndPointStatus       map[string]string                 `protobuf:"bytes,2,rep,name=endPointStatus,proto3" json:"endPointStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceStatus        *SmartLimiterStatus_ServiceStatus `protobuf:"bytes,3,opt,name=serviceStatus,proto3" json:"serviceStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SmartLimiterStatus) Reset()         { *m = SmartLimiterStatus{} }
func (m *SmartLimiterStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus) ProtoMessage()    {}
func (*SmartLimiterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{5}
}

func (m *SmartLimiterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus.Merge(m, src)
}
func (m *SmartLimiterStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus.Size(m)
}
func (m *SmartLimiterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus) GetRatelimitStatus() []*SmartLimitDescriptor {
	if m != nil {
		return m.RatelimitStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetEndPointStatus() map[string]string {
	if m != nil {
		return m.EndPointStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetServiceStatus() *SmartLimiterStatus_ServiceStatus {
	if m != nil {
		return m.ServiceStatus
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus struct {
	Selector             map[string]string                            `protobuf:"bytes,1,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Listener             []*SmartLimiterStatus_ServiceStatus_Listener `protobuf:"bytes,2,rep,name=listener,proto3" json:"listener,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus) Reset()         { *m = SmartLimiterStatus_ServiceStatus{} }
func (m *SmartLimiterStatus_ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus_ServiceStatus) ProtoMessage()    {}
func (*SmartLimiterStatus_ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{5, 1}
}

func (m *SmartLimiterStatus_ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *SmartLimiterStatus_ServiceStatus) GetListener() []*SmartLimiterStatus_ServiceStatus_Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus_Listener struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) Reset() {
	*m = SmartLimiterStatus_ServiceStatus_Listener{}
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus_ServiceStatus_Listener) ProtoMessage()    {}
func (*SmartLimiterStatus_ServiceStatus_Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{5, 1, 1}
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type HeaderMatcher struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExactMatch           string   `protobuf:"bytes,2,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`
	RegexMatch           string   `protobuf:"bytes,3,opt,name=regex_match,json=regexMatch,proto3" json:"regex_match,omitempty"`
	PresentMatch         bool     `protobuf:"varint,7,opt,name=present_match,json=presentMatch,proto3" json:"present_match,omitempty"`
	PrefixMatch          string   `protobuf:"bytes,9,opt,name=prefix_match,json=prefixMatch,proto3" json:"prefix_match,omitempty"`
	SuffixMatch          string   `protobuf:"bytes,10,opt,name=suffix_match,json=suffixMatch,proto3" json:"suffix_match,omitempty"`
	InvertMatch          bool     `protobuf:"varint,8,opt,name=invert_match,json=invertMatch,proto3" json:"invert_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderMatcher) Reset()         { *m = HeaderMatcher{} }
func (m *HeaderMatcher) String() string { return proto.CompactTextString(m) }
func (*HeaderMatcher) ProtoMessage()    {}
func (*HeaderMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{6}
}

func (m *HeaderMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderMatcher.Unmarshal(m, b)
}
func (m *HeaderMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderMatcher.Marshal(b, m, deterministic)
}
func (m *HeaderMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderMatcher.Merge(m, src)
}
func (m *HeaderMatcher) XXX_Size() int {
	return xxx_messageInfo_HeaderMatcher.Size(m)
}
func (m *HeaderMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderMatcher proto.InternalMessageInfo

func (m *HeaderMatcher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HeaderMatcher) GetExactMatch() string {
	if m != nil {
		return m.ExactMatch
	}
	return ""
}

func (m *HeaderMatcher) GetRegexMatch() string {
	if m != nil {
		return m.RegexMatch
	}
	return ""
}

func (m *HeaderMatcher) GetPresentMatch() bool {
	if m != nil {
		return m.PresentMatch
	}
	return false
}

func (m *HeaderMatcher) GetPrefixMatch() string {
	if m != nil {
		return m.PrefixMatch
	}
	return ""
}

func (m *HeaderMatcher) GetSuffixMatch() string {
	if m != nil {
		return m.SuffixMatch
	}
	return ""
}

func (m *HeaderMatcher) GetInvertMatch() bool {
	if m != nil {
		return m.InvertMatch
	}
	return false
}

func init() {
	proto.RegisterType((*Action)(nil), "netease.microservice.v1alpha1.Action")
	proto.RegisterType((*ActionStatus)(nil), "netease.microservice.v1alpha1.ActionStatus")
	proto.RegisterType((*SmartLimitDescriptor)(nil), "netease.microservice.v1alpha1.SmartLimitDescriptor")
	proto.RegisterType((*SmartLimitDescriptorStatus)(nil), "netease.microservice.v1alpha1.SmartLimitDescriptorStatus")
	proto.RegisterType((*SmartLimiterSpec)(nil), "netease.microservice.v1alpha1.SmartLimiterSpec")
	proto.RegisterType((*SmartLimiterStatus)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus")
	proto.RegisterMapType((map[string]string)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.EndPointStatusEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus")
	proto.RegisterMapType((map[string]string)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.SelectorEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus_Listener)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.Listener")
	proto.RegisterType((*HeaderMatcher)(nil), "netease.microservice.v1alpha1.HeaderMatcher")
}

func init() {
	proto.RegisterFile("pkg/apis/microservice/v1alpha1/smart_limiter.proto", fileDescriptor_76bfc6c51416fcda)
}

var fileDescriptor_76bfc6c51416fcda = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0x59, 0x6e, 0x13, 0x4d,
	0x10, 0xd6, 0xc4, 0x89, 0x7f, 0xbb, 0x1c, 0xff, 0x7f, 0xd4, 0x7f, 0x40, 0xc6, 0x62, 0x09, 0x46,
	0x48, 0x48, 0xa0, 0xb1, 0xe2, 0xf0, 0x80, 0x58, 0x95, 0x0d, 0x05, 0x29, 0x91, 0xa2, 0xb1, 0x78,
	0x41, 0x02, 0xab, 0x33, 0x53, 0x76, 0x5a, 0x99, 0x99, 0x1e, 0x7a, 0xda, 0x26, 0x7e, 0xe4, 0x00,
	0x9c, 0x87, 0x03, 0x70, 0x02, 0x6e, 0xc0, 0x1d, 0xb8, 0x00, 0xbd, 0xd9, 0xb1, 0x23, 0x2b, 0x0b,
	0xc9, 0xdb, 0x74, 0xf9, 0x5b, 0xaa, 0xaa, 0xbb, 0x5c, 0xd0, 0xca, 0x8e, 0x7a, 0x4d, 0x9a, 0xb1,
	0xbc, 0x99, 0xb0, 0x50, 0xf0, 0x1c, 0xc5, 0x80, 0x85, 0xd8, 0x1c, 0xac, 0xd2, 0x38, 0x3b, 0xa4,
	0xab, 0xcd, 0x3c, 0xa1, 0x42, 0x76, 0x62, 0x96, 0x30, 0x89, 0xc2, 0xcf, 0x04, 0x97, 0x9c, 0xdc,
	0x49, 0x51, 0x22, 0xcd, 0xd1, 0x9f, 0xa4, 0xf8, 0x23, 0x4a, 0xfd, 0x6e, 0x8f, 0xf3, 0x5e, 0x8c,
	0x4d, 0x03, 0x3e, 0xe8, 0x77, 0x9b, 0x51, 0x5f, 0x50, 0xc9, 0x78, 0x6a, 0xe9, 0x8d, 0x4f, 0x50,
	0x5c, 0x0f, 0xf5, 0x99, 0x2c, 0xc3, 0xc2, 0xe7, 0x3e, 0x97, 0xb4, 0xe6, 0xad, 0x78, 0x8f, 0xca,
	0x81, 0x3d, 0x90, 0xd7, 0x50, 0xed, 0xb2, 0x38, 0xee, 0xb0, 0x54, 0x59, 0x0e, 0x68, 0x5c, 0x9b,
	0x53, 0xbf, 0x56, 0x5a, 0xb7, 0x7c, 0xab, 0xeb, 0x8f, 0x74, 0xfd, 0x2d, 0xa7, 0x1b, 0x2c, 0x6a,
	0xfc, 0x3b, 0x07, 0x6f, 0x44, 0xb0, 0x68, 0xf5, 0xdb, 0x92, 0xca, 0x7e, 0x3e, 0xed, 0x52, 0xbd,
	0x2e, 0x97, 0xef, 0x1e, 0x2c, 0xb7, 0x75, 0x73, 0x76, 0x75, 0x6f, 0xb6, 0x30, 0x0f, 0x05, 0xcb,
	0x24, 0x17, 0xe4, 0x36, 0x94, 0x43, 0x9e, 0x46, 0x4c, 0x73, 0x8c, 0x68, 0x39, 0x38, 0x09, 0x90,
	0x57, 0x50, 0xa4, 0x26, 0xb9, 0x5a, 0xc1, 0xf8, 0x3d, 0xf4, 0xcf, 0x6c, 0xa6, 0x6f, 0x2b, 0x09,
	0x1c, 0x89, 0x6c, 0xc0, 0x42, 0x42, 0x65, 0x78, 0x58, 0x9b, 0x5f, 0x29, 0x28, 0xf6, 0x93, 0x73,
	0xd8, 0x3b, 0x48, 0x23, 0x14, 0x7b, 0x9a, 0x81, 0x22, 0xb0, 0xd4, 0xc6, 0x0f, 0x0f, 0xea, 0xb3,
	0x32, 0x77, 0xed, 0x3a, 0x3b, 0xff, 0xcd, 0x53, 0xf9, 0x3f, 0xbe, 0x50, 0xfe, 0x56, 0xfa, 0x5a,
	0xab, 0xf8, 0xea, 0xc1, 0xd2, 0x49, 0x15, 0x28, 0xda, 0x19, 0x86, 0xe4, 0x26, 0x14, 0x23, 0x9e,
	0x50, 0x96, 0xba, 0x17, 0xe5, 0x4e, 0xe4, 0x3d, 0x54, 0xa2, 0x71, 0x9d, 0xb9, 0xaa, 0x4a, 0xdb,
	0xae, 0x9d, 0x63, 0x3b, 0xab, 0x47, 0xc1, 0xa4, 0x4e, 0xe3, 0xd7, 0x02, 0x90, 0xa9, 0x1c, 0x6c,
	0x07, 0x3f, 0xc2, 0x7f, 0xea, 0xc9, 0xa0, 0x19, 0x1a, 0x1b, 0x52, 0xe9, 0xfc, 0xb5, 0xe3, 0x69,
	0x2d, 0x92, 0xc0, 0xbf, 0x98, 0x46, 0xfb, 0x5c, 0xbd, 0x5c, 0xa7, 0x6e, 0xeb, 0xd9, 0xbe, 0xb0,
	0xfa, 0x28, 0x53, 0x7f, 0x7b, 0x4a, 0x67, 0x3b, 0x95, 0x62, 0x18, 0x9c, 0x12, 0x27, 0x08, 0x55,
	0x27, 0xe5, 0xdc, 0xec, 0xc5, 0xbf, 0xb9, 0xbc, 0x5b, 0x7b, 0x52, 0x26, 0x98, 0x56, 0xad, 0xaf,
	0xc3, 0xff, 0x33, 0xb2, 0x21, 0x4b, 0x50, 0x38, 0xc2, 0xa1, 0xbb, 0x4e, 0xfd, 0xa9, 0xc7, 0x59,
	0xcd, 0x5f, 0x1f, 0xdd, 0xdb, 0xb4, 0x87, 0xe7, 0x73, 0xcf, 0xbc, 0xfa, 0xcf, 0x39, 0xa8, 0x4e,
	0x79, 0x10, 0x06, 0xa5, 0x1c, 0x63, 0x0c, 0x55, 0x1f, 0xdd, 0x15, 0xec, 0x5d, 0x31, 0x6d, 0x75,
	0xb2, 0x7a, 0xb6, 0x59, 0x63, 0x79, 0x12, 0x41, 0x29, 0x66, 0xb9, 0xc4, 0x14, 0x85, 0xbb, 0x8f,
	0x9d, 0xab, 0x5a, 0xed, 0x3a, 0xbd, 0x60, 0xac, 0x5c, 0x7f, 0xa1, 0x2b, 0x9c, 0x48, 0xe0, 0x52,
	0xfd, 0x69, 0x41, 0x69, 0x24, 0x49, 0x08, 0xcc, 0xa7, 0x34, 0x41, 0x47, 0x34, 0xdf, 0x3a, 0x96,
	0x71, 0x21, 0x0d, 0xb1, 0x1a, 0x98, 0xef, 0xc6, 0x6f, 0x0f, 0xaa, 0x53, 0xf3, 0x37, 0x93, 0x79,
	0x0f, 0x2a, 0x78, 0xac, 0x86, 0xbb, 0x63, 0xc7, 0xda, 0x3a, 0x83, 0x09, 0x19, 0x9a, 0x06, 0x08,
	0xec, 0xe1, 0xb1, 0x03, 0x14, 0x2c, 0xc0, 0x84, 0x2c, 0xe0, 0x01, 0x54, 0x33, 0x81, 0x39, 0xa6,
	0x23, 0x8d, 0x7f, 0x14, 0xa4, 0x14, 0x2c, 0xba, 0xa0, 0x05, 0xdd, 0x07, 0x7d, 0xee, 0xb2, 0x91,
	0x4c, 0xd9, 0xc8, 0x54, 0x6c, 0x6c, 0x0c, 0xc9, 0xfb, 0xdd, 0x13, 0x08, 0x58, 0x88, 0x8d, 0x8d,
	0x21, 0x2c, 0x1d, 0xa0, 0x18, 0x39, 0x95, 0x8c, 0x53, 0xc5, 0xc6, 0x0c, 0x64, 0xe3, 0x9b, 0x07,
	0x2f, 0x19, 0xf7, 0x31, 0x1d, 0xf0, 0xa1, 0x5a, 0x04, 0xc7, 0x43, 0xfb, 0xe9, 0xab, 0xff, 0xc1,
	0x2e, 0xeb, 0xf9, 0x6a, 0x11, 0xe8, 0x6d, 0x78, 0x28, 0x65, 0xe6, 0xc7, 0x3c, 0xa4, 0x71, 0xa7,
	0x1b, 0xf3, 0x2f, 0x1d, 0xf5, 0xab, 0x14, 0x3c, 0xf6, 0x07, 0xad, 0x8d, 0x1b, 0xbb, 0x3a, 0xfc,
	0x56, 0x45, 0x37, 0x6d, 0x70, 0x5f, 0xaf, 0x93, 0x7d, 0xef, 0xc3, 0xd3, 0x61, 0x3f, 0x1d, 0xbf,
	0x8b, 0x90, 0x27, 0xcd, 0x5c, 0x8d, 0xb6, 0xda, 0x95, 0x67, 0x6e, 0xe1, 0x83, 0xa2, 0xd9, 0x46,
	0x6b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc1, 0x73, 0x72, 0xae, 0x07, 0x00, 0x00,
}
