// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: plugin_module.proto

package config

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for PluginModule
func (this *PluginModule) MarshalJSON() ([]byte, error) {
	str, err := PluginModuleMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PluginModule
func (this *PluginModule) UnmarshalJSON(b []byte) error {
	return PluginModuleUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	PluginModuleMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	PluginModuleUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
