// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/gateway_plugin.proto

package istio

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Plugins_ListenerType int32

const (
	Plugins_Outbound Plugins_ListenerType = 0
	Plugins_Inbound  Plugins_ListenerType = 1
)

var Plugins_ListenerType_name = map[int32]string{
	0: "Outbound",
	1: "Inbound",
}

var Plugins_ListenerType_value = map[string]int32{
	"Outbound": 0,
	"Inbound":  1,
}

func (x Plugins_ListenerType) String() string {
	return proto.EnumName(Plugins_ListenerType_name, int32(x))
}

func (Plugins_ListenerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fde08958efb731f8, []int{1, 0}
}

type GatewayPlugin struct {
	// route level plugin
	Route []string `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	// host level plugin
	Host []string `protobuf:"bytes,2,rep,name=host,proto3" json:"host,omitempty"`
	// service level plugin
	Service []string   `protobuf:"bytes,3,rep,name=service,proto3" json:"service,omitempty"`
	Plugins []*Plugins `protobuf:"bytes,4,rep,name=plugins,proto3" json:"plugins,omitempty"`
	// which gateway should use this plugin setting
	Gateway []string `protobuf:"bytes,5,rep,name=gateway,proto3" json:"gateway,omitempty"`
	// which user should use this plugin setting
	User []string `protobuf:"bytes,6,rep,name=user,proto3" json:"user,omitempty"`
	// group setting 用于路由组级别的配置设置，其优先级低于路由级别的配置
	IsGroupSetting bool `protobuf:"varint,7,opt,name=isGroupSetting,proto3" json:"isGroupSetting,omitempty"`
	// listener level
	Listener             []*GatewayPlugin_Listener `protobuf:"bytes,8,rep,name=listener,proto3" json:"listener,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GatewayPlugin) Reset()         { *m = GatewayPlugin{} }
func (m *GatewayPlugin) String() string { return proto.CompactTextString(m) }
func (*GatewayPlugin) ProtoMessage()    {}
func (*GatewayPlugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde08958efb731f8, []int{0}
}
func (m *GatewayPlugin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GatewayPlugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GatewayPlugin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GatewayPlugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayPlugin.Merge(m, src)
}
func (m *GatewayPlugin) XXX_Size() int {
	return m.Size()
}
func (m *GatewayPlugin) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayPlugin.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayPlugin proto.InternalMessageInfo

func (m *GatewayPlugin) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *GatewayPlugin) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *GatewayPlugin) GetService() []string {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *GatewayPlugin) GetPlugins() []*Plugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *GatewayPlugin) GetGateway() []string {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *GatewayPlugin) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GatewayPlugin) GetIsGroupSetting() bool {
	if m != nil {
		return m.IsGroupSetting
	}
	return false
}

func (m *GatewayPlugin) GetListener() []*GatewayPlugin_Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

type GatewayPlugin_Listener struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Outbound             bool     `protobuf:"varint,2,opt,name=outbound,proto3" json:"outbound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayPlugin_Listener) Reset()         { *m = GatewayPlugin_Listener{} }
func (m *GatewayPlugin_Listener) String() string { return proto.CompactTextString(m) }
func (*GatewayPlugin_Listener) ProtoMessage()    {}
func (*GatewayPlugin_Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde08958efb731f8, []int{0, 0}
}
func (m *GatewayPlugin_Listener) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GatewayPlugin_Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GatewayPlugin_Listener.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GatewayPlugin_Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayPlugin_Listener.Merge(m, src)
}
func (m *GatewayPlugin_Listener) XXX_Size() int {
	return m.Size()
}
func (m *GatewayPlugin_Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayPlugin_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayPlugin_Listener proto.InternalMessageInfo

func (m *GatewayPlugin_Listener) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GatewayPlugin_Listener) GetOutbound() bool {
	if m != nil {
		return m.Outbound
	}
	return false
}

type Plugins struct {
	// plugin name is the name of plugin, such as envoy.util, com.netease.transformation
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// plugin settings
	Settings             *types.Struct        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	ListenerType         Plugins_ListenerType `protobuf:"varint,3,opt,name=listenerType,proto3,enum=istio.networking.v1alpha3.Plugins_ListenerType" json:"listenerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Plugins) Reset()         { *m = Plugins{} }
func (m *Plugins) String() string { return proto.CompactTextString(m) }
func (*Plugins) ProtoMessage()    {}
func (*Plugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde08958efb731f8, []int{1}
}
func (m *Plugins) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Plugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Plugins.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Plugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugins.Merge(m, src)
}
func (m *Plugins) XXX_Size() int {
	return m.Size()
}
func (m *Plugins) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugins.DiscardUnknown(m)
}

var xxx_messageInfo_Plugins proto.InternalMessageInfo

func (m *Plugins) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugins) GetSettings() *types.Struct {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Plugins) GetListenerType() Plugins_ListenerType {
	if m != nil {
		return m.ListenerType
	}
	return Plugins_Outbound
}

func init() {
	proto.RegisterEnum("istio.networking.v1alpha3.Plugins_ListenerType", Plugins_ListenerType_name, Plugins_ListenerType_value)
	proto.RegisterType((*GatewayPlugin)(nil), "istio.networking.v1alpha3.GatewayPlugin")
	proto.RegisterType((*GatewayPlugin_Listener)(nil), "istio.networking.v1alpha3.GatewayPlugin.Listener")
	proto.RegisterType((*Plugins)(nil), "istio.networking.v1alpha3.plugins")
}

func init() {
	proto.RegisterFile("networking/v1alpha3/gateway_plugin.proto", fileDescriptor_fde08958efb731f8)
}

var fileDescriptor_fde08958efb731f8 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcb, 0xae, 0xd3, 0x30,
	0x10, 0x86, 0x71, 0x6f, 0x49, 0xdd, 0x8b, 0x90, 0x85, 0x84, 0xa9, 0x50, 0x15, 0x65, 0x81, 0xc2,
	0xc6, 0x51, 0xdb, 0x1d, 0x62, 0xc5, 0xa6, 0x42, 0x02, 0x81, 0x5c, 0x56, 0x6c, 0x50, 0x5a, 0x4c,
	0x6a, 0x11, 0xec, 0xc8, 0x97, 0x56, 0x7d, 0x43, 0x96, 0x88, 0x27, 0x40, 0x7d, 0x04, 0x9e, 0xe0,
	0x28, 0x76, 0x92, 0x73, 0x7a, 0x74, 0x2e, 0xbb, 0x99, 0xc9, 0xfc, 0x7f, 0xbe, 0x99, 0x31, 0x4c,
	0x04, 0x33, 0x47, 0xa9, 0x7e, 0x72, 0x91, 0xa7, 0x87, 0x45, 0x56, 0x94, 0xfb, 0x6c, 0x95, 0xe6,
	0x99, 0x61, 0xc7, 0xec, 0xf4, 0xad, 0x2c, 0x6c, 0xce, 0x05, 0x29, 0x95, 0x34, 0x12, 0xbd, 0xe0,
	0xda, 0x70, 0x49, 0xae, 0xfb, 0x49, 0xd3, 0x3f, 0x7b, 0x99, 0x4b, 0x99, 0x17, 0x2c, 0x75, 0x8d,
	0x5b, 0xfb, 0x23, 0xd5, 0x46, 0xd9, 0x9d, 0xf1, 0xc2, 0xf8, 0x7f, 0x07, 0x4e, 0xd6, 0xde, 0xf1,
	0xb3, 0x33, 0x44, 0xcf, 0x60, 0x5f, 0x49, 0x6b, 0x18, 0x06, 0x51, 0x37, 0x19, 0x52, 0x9f, 0x20,
	0x04, 0x7b, 0x7b, 0xa9, 0x0d, 0xee, 0xb8, 0xa2, 0x8b, 0x11, 0x86, 0x81, 0x66, 0xea, 0xc0, 0x77,
	0x0c, 0x77, 0x5d, 0xb9, 0x49, 0xd1, 0x5b, 0x18, 0x78, 0x3c, 0x8d, 0x7b, 0x51, 0x37, 0x19, 0x2d,
	0x63, 0x72, 0x2f, 0x20, 0xa9, 0x3b, 0x69, 0x23, 0xa9, 0x7c, 0xeb, 0x21, 0x71, 0xdf, 0xfb, 0xd6,
	0x69, 0x45, 0x61, 0x35, 0x53, 0x78, 0xe0, 0x29, 0xaa, 0x18, 0xbd, 0x82, 0x53, 0xae, 0xd7, 0x4a,
	0xda, 0x72, 0xc3, 0x8c, 0xe1, 0x22, 0xc7, 0x41, 0x04, 0x92, 0x90, 0xde, 0xaa, 0xa2, 0x8f, 0x30,
	0x2c, 0xb8, 0x36, 0x4c, 0x30, 0x85, 0x43, 0x07, 0xb5, 0x78, 0x00, 0xea, 0x62, 0x27, 0xe4, 0x43,
	0x2d, 0xa4, 0xad, 0xc5, 0xec, 0x0d, 0x0c, 0x9b, 0x6a, 0x85, 0x55, 0x4a, 0x65, 0x30, 0x88, 0x40,
	0x32, 0xa1, 0x2e, 0x46, 0x33, 0x18, 0x4a, 0x6b, 0xb6, 0xd2, 0x8a, 0xef, 0xb8, 0xe3, 0x80, 0xda,
	0x3c, 0xfe, 0x0b, 0xda, 0xfd, 0x54, 0x5a, 0x91, 0xfd, 0x62, 0x4e, 0x3b, 0xa4, 0x2e, 0x46, 0x2b,
	0x18, 0x6a, 0x4f, 0xad, 0x9d, 0x76, 0xb4, 0x7c, 0x4e, 0xfc, 0x15, 0x49, 0x73, 0x45, 0xb2, 0x71,
	0x57, 0xa4, 0x6d, 0x23, 0xda, 0xc0, 0x71, 0x03, 0xf7, 0xe5, 0x54, 0x56, 0x27, 0x01, 0xc9, 0x74,
	0x99, 0x3e, 0xbe, 0xf8, 0x76, 0xba, 0x4a, 0x46, 0x2f, 0x4c, 0xe2, 0xd7, 0x70, 0x7c, 0xf3, 0x2b,
	0x1a, 0xc3, 0xf0, 0x53, 0x3d, 0xc5, 0xd3, 0x27, 0x68, 0x04, 0x83, 0xf7, 0xc2, 0x27, 0xe0, 0x1d,
	0xf9, 0x7d, 0x9e, 0x83, 0x3f, 0xe7, 0x39, 0xf8, 0x77, 0x9e, 0x83, 0xaf, 0x91, 0xff, 0x2d, 0x97,
	0x69, 0x56, 0xf2, 0xf4, 0x8e, 0x77, 0xbc, 0x1d, 0xb8, 0x51, 0x56, 0x57, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0x42, 0xef, 0x5d, 0xe5, 0x02, 0x00, 0x00,
}

func (m *GatewayPlugin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GatewayPlugin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GatewayPlugin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Listener) > 0 {
		for iNdEx := len(m.Listener) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Listener[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGatewayPlugin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.IsGroupSetting {
		i--
		if m.IsGroupSetting {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.User) > 0 {
		for iNdEx := len(m.User) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.User[iNdEx])
			copy(dAtA[i:], m.User[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.User[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Gateway) > 0 {
		for iNdEx := len(m.Gateway) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Gateway[iNdEx])
			copy(dAtA[i:], m.Gateway[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Gateway[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Plugins) > 0 {
		for iNdEx := len(m.Plugins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Plugins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGatewayPlugin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Service) > 0 {
		for iNdEx := len(m.Service) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Service[iNdEx])
			copy(dAtA[i:], m.Service[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Service[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Host) > 0 {
		for iNdEx := len(m.Host) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Host[iNdEx])
			copy(dAtA[i:], m.Host[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Host[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Route) > 0 {
		for iNdEx := len(m.Route) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Route[iNdEx])
			copy(dAtA[i:], m.Route[iNdEx])
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Route[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GatewayPlugin_Listener) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GatewayPlugin_Listener) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GatewayPlugin_Listener) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Outbound {
		i--
		if m.Outbound {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Port != 0 {
		i = encodeVarintGatewayPlugin(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Plugins) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Plugins) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Plugins) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ListenerType != 0 {
		i = encodeVarintGatewayPlugin(dAtA, i, uint64(m.ListenerType))
		i--
		dAtA[i] = 0x18
	}
	if m.Settings != nil {
		{
			size, err := m.Settings.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGatewayPlugin(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGatewayPlugin(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGatewayPlugin(dAtA []byte, offset int, v uint64) int {
	offset -= sovGatewayPlugin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GatewayPlugin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Route) > 0 {
		for _, s := range m.Route {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Host) > 0 {
		for _, s := range m.Host {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Service) > 0 {
		for _, s := range m.Service {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Plugins) > 0 {
		for _, e := range m.Plugins {
			l = e.Size()
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.Gateway) > 0 {
		for _, s := range m.Gateway {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if len(m.User) > 0 {
		for _, s := range m.User {
			l = len(s)
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if m.IsGroupSetting {
		n += 2
	}
	if len(m.Listener) > 0 {
		for _, e := range m.Listener {
			l = e.Size()
			n += 1 + l + sovGatewayPlugin(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GatewayPlugin_Listener) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Port != 0 {
		n += 1 + sovGatewayPlugin(uint64(m.Port))
	}
	if m.Outbound {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Plugins) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGatewayPlugin(uint64(l))
	}
	if m.Settings != nil {
		l = m.Settings.Size()
		n += 1 + l + sovGatewayPlugin(uint64(l))
	}
	if m.ListenerType != 0 {
		n += 1 + sovGatewayPlugin(uint64(m.ListenerType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovGatewayPlugin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGatewayPlugin(x uint64) (n int) {
	return sovGatewayPlugin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GatewayPlugin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GatewayPlugin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GatewayPlugin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Route", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Route = append(m.Route, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = append(m.Host, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Service = append(m.Service, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plugins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Plugins = append(m.Plugins, &Plugins{})
			if err := m.Plugins[len(m.Plugins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gateway = append(m.Gateway, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = append(m.User, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsGroupSetting", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsGroupSetting = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Listener", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Listener = append(m.Listener, &GatewayPlugin_Listener{})
			if err := m.Listener[len(m.Listener)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayPlugin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GatewayPlugin_Listener) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Listener: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Listener: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outbound", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Outbound = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayPlugin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Plugins) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: plugins: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: plugins: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Settings == nil {
				m.Settings = &types.Struct{}
			}
			if err := m.Settings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListenerType", wireType)
			}
			m.ListenerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ListenerType |= Plugins_ListenerType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayPlugin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayPlugin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGatewayPlugin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGatewayPlugin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayPlugin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGatewayPlugin
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGatewayPlugin
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGatewayPlugin
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGatewayPlugin(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGatewayPlugin
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGatewayPlugin = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGatewayPlugin   = fmt.Errorf("proto: integer overflow")
)
