apiVersion: apps/v1
kind: Deployment
metadata:
  name: slime-boot
  namespace: mesh-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slime-boot
  template:
    metadata:
      labels:
        name: slime-boot
    spec:
      serviceAccountName: slime-boot
      imagePullSecrets:
        - name: slime-secret
      containers:
        - name: slime-boot
          # Replace this with the built image name
          image: docker.pkg.github.com/slime-io/slime/slime-boot:v0.1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "slime-boot"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: slime-boot
  namespace: mesh-operator
subjects:
  - kind: ServiceAccount
    name: slime-boot
    namespace: mesh-operator
roleRef:
  kind: Role
  name: slime-boot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slime-boot
  namespace: mesh-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slime-boot
subjects:
  - kind: ServiceAccount
    name: slime-boot
    namespace: mesh-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wa2cuZ2l0aHViLmNvbS92MiI6eyJ1c2VybmFtZSI6InNsaW1lIiwicGFzc3dvcmQiOiJnaHBfRDFkR1RzeUJjMDdIWUNEV3FvVVJRYk1KY0h2TU5kNEF5QVFYIiwiYXV0aCI6ImMyeHBiV1U2WjJod1gwUXhaRWRVYzNsQ1l6QTNTRmxEUkZkeGIxVlNVV0pOU21OSWRrMU9aRFJCZVVGUldBPT0ifX19
kind: Secret
metadata:
  name: slime-secret
  namespace: mesh-operator
type: kubernetes.io/dockerconfigjson

