---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: slimeboots.config.netease.com
spec:
  group: config.netease.com
  names:
    shortNames:
      - slb
    kind: SlimeBoot
    listKind: SlimeBootList
    plural: slimeboots
    singular: slimeboot
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: 'SlimeBoot is useful for deploy'
              type: object
              properties:
                replicaCount:
                  type: integer
                args:
                  type: array
                  items:
                    type: string
                image:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                serviceAccount:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                podAnnotations:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                podSecurityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                resources:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                autoscaling:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                nodeSelector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                affinity:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                namespace:
                  type: string
                istioNamespace:
                  type: string
                service:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                auxiliaryPort:
                  type: integer
                logSourcePort:
                  type: integer
                containers:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                volumes:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                module:
                  type: array
                  items:
                    type: object
                    properties:
                      limiter:
                        type: object
                        description: 'limiter parameters'
                        properties:
                          disableGlobalRateLimit:
                            type: boolean
                            description: 'disable GlobalRateLimit'
                          disableAdaptive:
                            type: boolean
                            description: 'disable use promql'
                          enableServiceEntry:
                            type: boolean
                            description: 'use se from from framework'
                          disableInsertLocalRateLimit:
                            type: boolean
                            description: 'it will not generate envoy.filters.http.local_ratelimit insert before http.router when true'
                          disableInsertGlobalRateLimit:
                            type: boolean
                            description: 'it will not generate envoy.filters.http.ratelimit insert before http.router when true'
                          rlsConfigMap:
                            type: object
                            description: 'specify the rls namespaces'
                            x-kubernetes-preserve-unknown-fields: true
                          domain:
                            description: 'specify domain, it is useful in global ratelimiter'
                            type: string
                          rls:
                            description: 'specify rls server address, if disableGlobalRateLimit if false'
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                      plugin:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      global:
                        type: object
                        properties:
                          service:
                            type: string
                          multicluster:
                            type: string
                          istioNamespace:
                            type: string
                          slimeNamespace:
                            type: string
                          log:
                            type: object
                            properties:
                              logLevel:
                                type: string
                              klogLevel:
                                type: integer
                              logRotate:
                                type: boolean
                              enableQuote:
                                type: boolean
                              logRotateConfig:
                                type: object
                                properties:
                                  filePath:
                                    type: string
                                  maxSizeMB:
                                    type: integer
                                  maxBackups:
                                    type: integer
                                  maxAgeDay:
                                    type: integer
                                  compress:
                                    type: boolean
                          misc:
                            type: object
                            additionalProperties:
                              type: string
                          istioRev:
                            type: string
                          strictRev:
                            type: boolean
                          selfResourceRev:
                            type: string
                          configSources:
                            type: array
                            items:
                              type: object
                              properties:
                                address:
                                  type: string
                          masterUrl:
                            type: string
                          configRev:
                            type: string
                          clientGoTokenBucket:
                            type: object
                            properties:
                              qps:
                                type: integer
                              burst:
                                type: integer
                      fence:
                        type: object
                        properties:
                          wormholePort:
                            description: "service ports enable lazyload"
                            type: array
                            items:
                              type: string
                          autoFence:
                            type: boolean
                            description: "whether enable ServiceFence auto generating, default value is false"
                          namespace:
                            type: array
                            description: "the namespace list which enable lazyload"
                            items:
                              type: string
                          dispatches:
                            type: array
                            description: 'custom outside dispatch traffic rules'
                            items:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                          domainAliases:
                            type: array
                            description: 'can convert to one or many domain alias rules'
                            items:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                          defaultFence:
                            description: 'default behavior of create fence or not when autoFence is true, default value is false'
                            type: boolean
                          autoPort:
                            description: 'whether enable http service port auto management, default value is false'
                            type: boolean
                      metric:
                        type: object
                        properties:
                          prometheus:
                            type: object
                            properties:
                              address:
                                type: string
                              handlers:
                                type: object
                                additionalProperties:
                                  type: object
                                  properties:
                                    query:
                                      type: string
                                    type:
                                      type: string
                                      enum:
                                        - Value
                                        - Group
                          k8s:
                            type: object
                            properties:
                              handlers:
                                type: array
                                items:
                                  type: string
                      name:
                        type: string
                      enable:
                        type: boolean
                      general:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      bundle:
                        type: object
                        properties:
                          modules:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                kind:
                                  type: string
                      mode:
                        type: string
                      kind:
                        type: string
                component:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}