// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Bar struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bar) Reset()         { *m = Bar{} }
func (m *Bar) String() string { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()    {}
func (*Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bar.Unmarshal(m, b)
}
func (m *Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bar.Marshal(b, m, deterministic)
}
func (m *Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bar.Merge(m, src)
}
func (m *Bar) XXX_Size() int {
	return xxx_messageInfo_Bar.Size(m)
}
func (m *Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Bar proto.InternalMessageInfo

func (m *Bar) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

type General struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  *Bar     `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *General) Reset()         { *m = General{} }
func (m *General) String() string { return proto.CompactTextString(m) }
func (*General) ProtoMessage()    {}
func (*General) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *General) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_General.Unmarshal(m, b)
}
func (m *General) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_General.Marshal(b, m, deterministic)
}
func (m *General) XXX_Merge(src proto.Message) {
	xxx_messageInfo_General.Merge(m, src)
}
func (m *General) XXX_Size() int {
	return xxx_messageInfo_General.Size(m)
}
func (m *General) XXX_DiscardUnknown() {
	xxx_messageInfo_General.DiscardUnknown(m)
}

var xxx_messageInfo_General proto.InternalMessageInfo

func (m *General) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *General) GetBar() *Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

func init() {
	proto.RegisterType((*Bar)(nil), "slime.microservice.v1alpha1.Bar")
	proto.RegisterType((*General)(nil), "slime.microservice.v1alpha1.General")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xbd, 0x4e, 0xc4, 0x30,
	0x10, 0x84, 0x65, 0x22, 0x81, 0x30, 0x57, 0x20, 0xd3, 0x9c, 0xa0, 0x89, 0xae, 0xba, 0x06, 0xaf,
	0x2e, 0xf0, 0x04, 0x69, 0x28, 0x91, 0xae, 0xa4, 0x5b, 0x9b, 0x8d, 0x63, 0xc9, 0xce, 0x5a, 0xce,
	0x8f, 0xf2, 0xf8, 0x28, 0x0e, 0xb4, 0x74, 0xdf, 0x68, 0x67, 0x56, 0x33, 0xf2, 0x60, 0x79, 0xe8,
	0xbc, 0xd3, 0x29, 0xf3, 0xc4, 0xea, 0x65, 0x0c, 0x3e, 0x92, 0x8e, 0xde, 0x66, 0x1e, 0x29, 0x2f,
	0xde, 0x92, 0x5e, 0x2e, 0x18, 0x52, 0x8f, 0x97, 0xe7, 0x57, 0xe7, 0xa7, 0x7e, 0x36, 0xda, 0x72,
	0x04, 0xc7, 0x8e, 0xa1, 0x64, 0xcc, 0xdc, 0x15, 0x55, 0x44, 0xa1, 0xfd, 0xd7, 0xe9, 0x49, 0x56,
	0x2d, 0x66, 0x75, 0x90, 0x62, 0x3d, 0x8a, 0x5a, 0x9c, 0xef, 0xaf, 0x62, 0x3d, 0x7d, 0xca, 0xbb,
	0x0f, 0x1a, 0x28, 0x63, 0x50, 0x8f, 0xb2, 0xea, 0x98, 0x7f, 0x4f, 0x1b, 0xaa, 0x46, 0x56, 0x06,
	0xf3, 0xf1, 0xa6, 0x16, 0xe7, 0x87, 0xa6, 0xd6, 0xff, 0x74, 0xd1, 0x2d, 0xe6, 0xeb, 0x66, 0x6e,
	0xdf, 0xbf, 0x9a, 0xdd, 0xe7, 0x19, 0x0a, 0x40, 0xe4, 0xef, 0x39, 0xd0, 0x08, 0xb4, 0x62, 0x4c,
	0x81, 0x00, 0x93, 0x87, 0x7d, 0x24, 0xfc, 0xc5, 0xcd, 0x6d, 0xa9, 0xf8, 0xf6, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0xd5, 0xd0, 0x01, 0xfe, 0x00, 0x00, 0x00,
}
