// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for MeshRegistryModule
func (this *MeshRegistryModule) MarshalJSON() ([]byte, error) {
	str, err := MeshregistryModuleMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshRegistryModule
func (this *MeshRegistryModule) UnmarshalJSON(b []byte) error {
	return MeshregistryModuleUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	MeshregistryModuleMarshaler   = &jsonpb.Marshaler{}
	MeshregistryModuleUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
