// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Limiter_RateLimitBackend int32

const (
	Limiter_netEaseLocalFlowControl Limiter_RateLimitBackend = 0
	Limiter_envoyLocalRateLimit     Limiter_RateLimitBackend = 1
)

var Limiter_RateLimitBackend_name = map[int32]string{
	0: "netEaseLocalFlowControl",
	1: "envoyLocalRateLimit",
}

var Limiter_RateLimitBackend_value = map[string]int32{
	"netEaseLocalFlowControl": 0,
	"envoyLocalRateLimit":     1,
}

func (x Limiter_RateLimitBackend) String() string {
	return proto.EnumName(Limiter_RateLimitBackend_name, int32(x))
}

func (Limiter_RateLimitBackend) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3, 0}
}

type Prometheus_Source_Type int32

const (
	Prometheus_Source_Value Prometheus_Source_Type = 0
	Prometheus_Source_Group Prometheus_Source_Type = 1
)

var Prometheus_Source_Type_name = map[int32]string{
	0: "Value",
	1: "Group",
}

var Prometheus_Source_Type_value = map[string]int32{
	"Value": 0,
	"Group": 1,
}

func (x Prometheus_Source_Type) String() string {
	return proto.EnumName(Prometheus_Source_Type_name, int32(x))
}

func (Prometheus_Source_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8, 0}
}

type Config_Mode int32

const (
	Config_Module     Config_Mode = 0
	Config_BundleItem Config_Mode = 1
)

var Config_Mode_name = map[int32]string{
	0: "Module",
	1: "BundleItem",
}

var Config_Mode_value = map[string]int32{
	"Module":     0,
	"BundleItem": 1,
}

func (x Config_Mode) String() string {
	return proto.EnumName(Config_Mode_name, int32(x))
}

func (Config_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{13, 0}
}

type LocalSource struct {
	Mount                string   `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalSource) Reset()         { *m = LocalSource{} }
func (m *LocalSource) String() string { return proto.CompactTextString(m) }
func (*LocalSource) ProtoMessage()    {}
func (*LocalSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *LocalSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalSource.Unmarshal(m, b)
}
func (m *LocalSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalSource.Marshal(b, m, deterministic)
}
func (m *LocalSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalSource.Merge(m, src)
}
func (m *LocalSource) XXX_Size() int {
	return xxx_messageInfo_LocalSource.Size(m)
}
func (m *LocalSource) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalSource.DiscardUnknown(m)
}

var xxx_messageInfo_LocalSource proto.InternalMessageInfo

func (m *LocalSource) GetMount() string {
	if m != nil {
		return m.Mount
	}
	return ""
}

type RemoteSource struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteSource) Reset()         { *m = RemoteSource{} }
func (m *RemoteSource) String() string { return proto.CompactTextString(m) }
func (*RemoteSource) ProtoMessage()    {}
func (*RemoteSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *RemoteSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteSource.Unmarshal(m, b)
}
func (m *RemoteSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteSource.Marshal(b, m, deterministic)
}
func (m *RemoteSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteSource.Merge(m, src)
}
func (m *RemoteSource) XXX_Size() int {
	return xxx_messageInfo_RemoteSource.Size(m)
}
func (m *RemoteSource) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteSource.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteSource proto.InternalMessageInfo

func (m *RemoteSource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Plugin struct {
	// Types that are valid to be assigned to WasmSource:
	//	*Plugin_Local
	//	*Plugin_Remote
	WasmSource           isPlugin_WasmSource `protobuf_oneof:"wasm_source"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}
func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

type isPlugin_WasmSource interface {
	isPlugin_WasmSource()
}

type Plugin_Local struct {
	Local *LocalSource `protobuf:"bytes,2,opt,name=local,proto3,oneof" json:"local,omitempty"`
}
type Plugin_Remote struct {
	Remote *RemoteSource `protobuf:"bytes,3,opt,name=remote,proto3,oneof" json:"remote,omitempty"`
}

func (*Plugin_Local) isPlugin_WasmSource()  {}
func (*Plugin_Remote) isPlugin_WasmSource() {}

func (m *Plugin) GetWasmSource() isPlugin_WasmSource {
	if m != nil {
		return m.WasmSource
	}
	return nil
}

func (m *Plugin) GetLocal() *LocalSource {
	if x, ok := m.GetWasmSource().(*Plugin_Local); ok {
		return x.Local
	}
	return nil
}

func (m *Plugin) GetRemote() *RemoteSource {
	if x, ok := m.GetWasmSource().(*Plugin_Remote); ok {
		return x.Remote
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Plugin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Plugin_Local)(nil),
		(*Plugin_Remote)(nil),
	}
}

type Limiter struct {
	Backend                Limiter_RateLimitBackend `protobuf:"varint,3,opt,name=backend,proto3,enum=slime.config.v1alpha1.Limiter_RateLimitBackend" json:"backend,omitempty"`
	Refresh                *time.Duration           `protobuf:"bytes,4,opt,name=refresh,proto3,stdduration" json:"refresh,omitempty"`
	DisableGlobalRateLimit bool                     `protobuf:"varint,5,opt,name=disableGlobalRateLimit,proto3" json:"disableGlobalRateLimit,omitempty"`
	DisableAdaptive        bool                     `protobuf:"varint,6,opt,name=disableAdaptive,proto3" json:"disableAdaptive,omitempty"`
	EnableServiceEntry     bool                     `protobuf:"varint,7,opt,name=enableServiceEntry,proto3" json:"enableServiceEntry,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *Limiter) Reset()         { *m = Limiter{} }
func (m *Limiter) String() string { return proto.CompactTextString(m) }
func (*Limiter) ProtoMessage()    {}
func (*Limiter) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}
func (m *Limiter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limiter.Unmarshal(m, b)
}
func (m *Limiter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limiter.Marshal(b, m, deterministic)
}
func (m *Limiter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limiter.Merge(m, src)
}
func (m *Limiter) XXX_Size() int {
	return xxx_messageInfo_Limiter.Size(m)
}
func (m *Limiter) XXX_DiscardUnknown() {
	xxx_messageInfo_Limiter.DiscardUnknown(m)
}

var xxx_messageInfo_Limiter proto.InternalMessageInfo

func (m *Limiter) GetBackend() Limiter_RateLimitBackend {
	if m != nil {
		return m.Backend
	}
	return Limiter_netEaseLocalFlowControl
}

func (m *Limiter) GetRefresh() *time.Duration {
	if m != nil {
		return m.Refresh
	}
	return nil
}

func (m *Limiter) GetDisableGlobalRateLimit() bool {
	if m != nil {
		return m.DisableGlobalRateLimit
	}
	return false
}

func (m *Limiter) GetDisableAdaptive() bool {
	if m != nil {
		return m.DisableAdaptive
	}
	return false
}

func (m *Limiter) GetEnableServiceEntry() bool {
	if m != nil {
		return m.EnableServiceEntry
	}
	return false
}

type Global struct {
	Service        string            `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Multicluster   string            `protobuf:"bytes,2,opt,name=multicluster,proto3" json:"multicluster,omitempty"`
	IstioNamespace string            `protobuf:"bytes,3,opt,name=istioNamespace,proto3" json:"istioNamespace,omitempty"`
	SlimeNamespace string            `protobuf:"bytes,4,opt,name=slimeNamespace,proto3" json:"slimeNamespace,omitempty"`
	Log            *Log              `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Misc           map[string]string `protobuf:"bytes,6,rep,name=misc,proto3" json:"misc,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IstioRev       string            `protobuf:"bytes,7,opt,name=istioRev,proto3" json:"istioRev,omitempty"`
	StrictRev      bool              `protobuf:"varint,8,opt,name=strictRev,proto3" json:"strictRev,omitempty"`
	// ConfigSource describes a source of configuration data for networking
	// rules, and other Istio configuration artifacts. Multiple data sources
	// can be configured for a single control plane.
	ConfigSources []*ConfigSource `protobuf:"bytes,9,rep,name=configSources,proto3" json:"configSources,omitempty"`
	// specify the address of k8s api-server instead of default value
	MasterUrl string `protobuf:"bytes,10,opt,name=masterUrl,proto3" json:"masterUrl,omitempty"`
	// configRev is the value used by slime configController to fetch/filter configs
	// in format comma-separated revisions, e.g. "1-11-1,prod"
	// will add istioRev to configRev if it exists
	ConfigRev string `protobuf:"bytes,11,opt,name=configRev,proto3" json:"configRev,omitempty"`
	// control the maximum QPS to the master from this client
	ClientGoTokenBucket *ClientGoTokenBucket `protobuf:"bytes,12,opt,name=clientGoTokenBucket,proto3" json:"clientGoTokenBucket,omitempty"`
	// if SelfResourceRev is specified, the value of SelfResourceRev will be patched to resources which generated by slime itself, just like serviceFence
	// smartlimiter/envoyplugin/pluginmanager is excluded because these envoyfilter are generated by users or higher-level services
	// envoyfilter/sidecar is excluded because these resources generated base on their owner resources
	SelfResourceRev string `protobuf:"bytes,13,opt,name=selfResourceRev,proto3" json:"selfResourceRev,omitempty"`
	// specify the istio-config-source from which we can get a configs-mirror of relevant istiod.
	IstioConfigSource    *ConfigSource `protobuf:"bytes,14,opt,name=istioConfigSource,proto3" json:"istioConfigSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Global) Reset()         { *m = Global{} }
func (m *Global) String() string { return proto.CompactTextString(m) }
func (*Global) ProtoMessage()    {}
func (*Global) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}
func (m *Global) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Global.Unmarshal(m, b)
}
func (m *Global) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Global.Marshal(b, m, deterministic)
}
func (m *Global) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Global.Merge(m, src)
}
func (m *Global) XXX_Size() int {
	return xxx_messageInfo_Global.Size(m)
}
func (m *Global) XXX_DiscardUnknown() {
	xxx_messageInfo_Global.DiscardUnknown(m)
}

var xxx_messageInfo_Global proto.InternalMessageInfo

func (m *Global) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Global) GetMulticluster() string {
	if m != nil {
		return m.Multicluster
	}
	return ""
}

func (m *Global) GetIstioNamespace() string {
	if m != nil {
		return m.IstioNamespace
	}
	return ""
}

func (m *Global) GetSlimeNamespace() string {
	if m != nil {
		return m.SlimeNamespace
	}
	return ""
}

func (m *Global) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Global) GetMisc() map[string]string {
	if m != nil {
		return m.Misc
	}
	return nil
}

func (m *Global) GetIstioRev() string {
	if m != nil {
		return m.IstioRev
	}
	return ""
}

func (m *Global) GetStrictRev() bool {
	if m != nil {
		return m.StrictRev
	}
	return false
}

func (m *Global) GetConfigSources() []*ConfigSource {
	if m != nil {
		return m.ConfigSources
	}
	return nil
}

func (m *Global) GetMasterUrl() string {
	if m != nil {
		return m.MasterUrl
	}
	return ""
}

func (m *Global) GetConfigRev() string {
	if m != nil {
		return m.ConfigRev
	}
	return ""
}

func (m *Global) GetClientGoTokenBucket() *ClientGoTokenBucket {
	if m != nil {
		return m.ClientGoTokenBucket
	}
	return nil
}

func (m *Global) GetSelfResourceRev() string {
	if m != nil {
		return m.SelfResourceRev
	}
	return ""
}

func (m *Global) GetIstioConfigSource() *ConfigSource {
	if m != nil {
		return m.IstioConfigSource
	}
	return nil
}

type Log struct {
	LogLevel             string           `protobuf:"bytes,1,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	KlogLevel            int32            `protobuf:"varint,2,opt,name=klogLevel,proto3" json:"klogLevel,omitempty"`
	LogRotate            bool             `protobuf:"varint,3,opt,name=logRotate,proto3" json:"logRotate,omitempty"`
	LogRotateConfig      *LogRotateConfig `protobuf:"bytes,4,opt,name=logRotateConfig,proto3" json:"logRotateConfig,omitempty"`
	EnableQuote          bool             `protobuf:"varint,5,opt,name=enableQuote,proto3" json:"enableQuote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *Log) GetKlogLevel() int32 {
	if m != nil {
		return m.KlogLevel
	}
	return 0
}

func (m *Log) GetLogRotate() bool {
	if m != nil {
		return m.LogRotate
	}
	return false
}

func (m *Log) GetLogRotateConfig() *LogRotateConfig {
	if m != nil {
		return m.LogRotateConfig
	}
	return nil
}

func (m *Log) GetEnableQuote() bool {
	if m != nil {
		return m.EnableQuote
	}
	return false
}

type LogRotateConfig struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	MaxSizeMB            int32    `protobuf:"varint,2,opt,name=maxSizeMB,proto3" json:"maxSizeMB,omitempty"`
	MaxBackups           int32    `protobuf:"varint,3,opt,name=maxBackups,proto3" json:"maxBackups,omitempty"`
	MaxAgeDay            int32    `protobuf:"varint,4,opt,name=maxAgeDay,proto3" json:"maxAgeDay,omitempty"`
	Compress             bool     `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRotateConfig) Reset()         { *m = LogRotateConfig{} }
func (m *LogRotateConfig) String() string { return proto.CompactTextString(m) }
func (*LogRotateConfig) ProtoMessage()    {}
func (*LogRotateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}
func (m *LogRotateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRotateConfig.Unmarshal(m, b)
}
func (m *LogRotateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRotateConfig.Marshal(b, m, deterministic)
}
func (m *LogRotateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRotateConfig.Merge(m, src)
}
func (m *LogRotateConfig) XXX_Size() int {
	return xxx_messageInfo_LogRotateConfig.Size(m)
}
func (m *LogRotateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRotateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogRotateConfig proto.InternalMessageInfo

func (m *LogRotateConfig) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *LogRotateConfig) GetMaxSizeMB() int32 {
	if m != nil {
		return m.MaxSizeMB
	}
	return 0
}

func (m *LogRotateConfig) GetMaxBackups() int32 {
	if m != nil {
		return m.MaxBackups
	}
	return 0
}

func (m *LogRotateConfig) GetMaxAgeDay() int32 {
	if m != nil {
		return m.MaxAgeDay
	}
	return 0
}

func (m *LogRotateConfig) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

type Fence struct {
	WormholePort         []string `protobuf:"bytes,2,rep,name=wormholePort,proto3" json:"wormholePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fence) Reset()         { *m = Fence{} }
func (m *Fence) String() string { return proto.CompactTextString(m) }
func (*Fence) ProtoMessage()    {}
func (*Fence) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{7}
}
func (m *Fence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fence.Unmarshal(m, b)
}
func (m *Fence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fence.Marshal(b, m, deterministic)
}
func (m *Fence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fence.Merge(m, src)
}
func (m *Fence) XXX_Size() int {
	return xxx_messageInfo_Fence.Size(m)
}
func (m *Fence) XXX_DiscardUnknown() {
	xxx_messageInfo_Fence.DiscardUnknown(m)
}

var xxx_messageInfo_Fence proto.InternalMessageInfo

func (m *Fence) GetWormholePort() []string {
	if m != nil {
		return m.WormholePort
	}
	return nil
}

type Prometheus_Source struct {
	Address              string                                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Handlers             map[string]*Prometheus_Source_Handler `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Prometheus_Source) Reset()         { *m = Prometheus_Source{} }
func (m *Prometheus_Source) String() string { return proto.CompactTextString(m) }
func (*Prometheus_Source) ProtoMessage()    {}
func (*Prometheus_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8}
}
func (m *Prometheus_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prometheus_Source.Unmarshal(m, b)
}
func (m *Prometheus_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prometheus_Source.Marshal(b, m, deterministic)
}
func (m *Prometheus_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prometheus_Source.Merge(m, src)
}
func (m *Prometheus_Source) XXX_Size() int {
	return xxx_messageInfo_Prometheus_Source.Size(m)
}
func (m *Prometheus_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Prometheus_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Prometheus_Source proto.InternalMessageInfo

func (m *Prometheus_Source) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Prometheus_Source) GetHandlers() map[string]*Prometheus_Source_Handler {
	if m != nil {
		return m.Handlers
	}
	return nil
}

type Prometheus_Source_Handler struct {
	Query                string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type                 Prometheus_Source_Type `protobuf:"varint,2,opt,name=type,proto3,enum=slime.config.v1alpha1.Prometheus_Source_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Prometheus_Source_Handler) Reset()         { *m = Prometheus_Source_Handler{} }
func (m *Prometheus_Source_Handler) String() string { return proto.CompactTextString(m) }
func (*Prometheus_Source_Handler) ProtoMessage()    {}
func (*Prometheus_Source_Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8, 0}
}
func (m *Prometheus_Source_Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prometheus_Source_Handler.Unmarshal(m, b)
}
func (m *Prometheus_Source_Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prometheus_Source_Handler.Marshal(b, m, deterministic)
}
func (m *Prometheus_Source_Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prometheus_Source_Handler.Merge(m, src)
}
func (m *Prometheus_Source_Handler) XXX_Size() int {
	return xxx_messageInfo_Prometheus_Source_Handler.Size(m)
}
func (m *Prometheus_Source_Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Prometheus_Source_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Prometheus_Source_Handler proto.InternalMessageInfo

func (m *Prometheus_Source_Handler) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Prometheus_Source_Handler) GetType() Prometheus_Source_Type {
	if m != nil {
		return m.Type
	}
	return Prometheus_Source_Value
}

type K8S_Source struct {
	Handlers             []string `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8S_Source) Reset()         { *m = K8S_Source{} }
func (m *K8S_Source) String() string { return proto.CompactTextString(m) }
func (*K8S_Source) ProtoMessage()    {}
func (*K8S_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{9}
}
func (m *K8S_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8S_Source.Unmarshal(m, b)
}
func (m *K8S_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8S_Source.Marshal(b, m, deterministic)
}
func (m *K8S_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8S_Source.Merge(m, src)
}
func (m *K8S_Source) XXX_Size() int {
	return xxx_messageInfo_K8S_Source.Size(m)
}
func (m *K8S_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_K8S_Source.DiscardUnknown(m)
}

var xxx_messageInfo_K8S_Source proto.InternalMessageInfo

func (m *K8S_Source) GetHandlers() []string {
	if m != nil {
		return m.Handlers
	}
	return nil
}

type Metric struct {
	Prometheus           *Prometheus_Source `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	K8S                  *K8S_Source        `protobuf:"bytes,2,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{10}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetPrometheus() *Prometheus_Source {
	if m != nil {
		return m.Prometheus
	}
	return nil
}

func (m *Metric) GetK8S() *K8S_Source {
	if m != nil {
		return m.K8S
	}
	return nil
}

type General struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *General) Reset()         { *m = General{} }
func (m *General) String() string { return proto.CompactTextString(m) }
func (*General) ProtoMessage()    {}
func (*General) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{11}
}
func (m *General) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_General.Unmarshal(m, b)
}
func (m *General) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_General.Marshal(b, m, deterministic)
}
func (m *General) XXX_Merge(src proto.Message) {
	xxx_messageInfo_General.Merge(m, src)
}
func (m *General) XXX_Size() int {
	return xxx_messageInfo_General.Size(m)
}
func (m *General) XXX_DiscardUnknown() {
	xxx_messageInfo_General.DiscardUnknown(m)
}

var xxx_messageInfo_General proto.InternalMessageInfo

type Bundle struct {
	Modules              []*Bundle_Item `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{12}
}
func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle.Unmarshal(m, b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
}
func (m *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(m, src)
}
func (m *Bundle) XXX_Size() int {
	return xxx_messageInfo_Bundle.Size(m)
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetModules() []*Bundle_Item {
	if m != nil {
		return m.Modules
	}
	return nil
}

type Bundle_Item struct {
	// submodule name, custom value, necessary
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// submodule kind, can only be one of real module kinds, like limiter, necessary
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bundle_Item) Reset()         { *m = Bundle_Item{} }
func (m *Bundle_Item) String() string { return proto.CompactTextString(m) }
func (*Bundle_Item) ProtoMessage()    {}
func (*Bundle_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{12, 0}
}
func (m *Bundle_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle_Item.Unmarshal(m, b)
}
func (m *Bundle_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle_Item.Marshal(b, m, deterministic)
}
func (m *Bundle_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle_Item.Merge(m, src)
}
func (m *Bundle_Item) XXX_Size() int {
	return xxx_messageInfo_Bundle_Item.Size(m)
}
func (m *Bundle_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle_Item proto.InternalMessageInfo

func (m *Bundle_Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bundle_Item) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type Config struct {
	Plugin  *Plugin     `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Limiter *Limiter    `protobuf:"bytes,2,opt,name=limiter,proto3" json:"limiter,omitempty"`
	Global  *Global     `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	Fence   *Fence      `protobuf:"bytes,4,opt,name=fence,proto3" json:"fence,omitempty"`
	Metric  *Metric     `protobuf:"bytes,6,opt,name=metric,proto3" json:"metric,omitempty"`
	Name    string      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Enable  bool        `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty"`
	General *General    `protobuf:"bytes,8,opt,name=general,proto3" json:"general,omitempty"`
	Bundle  *Bundle     `protobuf:"bytes,9,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Mode    Config_Mode `protobuf:"varint,10,opt,name=mode,proto3,enum=slime.config.v1alpha1.Config_Mode" json:"mode,omitempty"`
	// like bundle item kind, necessary if not bundle
	Kind                 string   `protobuf:"bytes,11,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{13}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetPlugin() *Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *Config) GetLimiter() *Limiter {
	if m != nil {
		return m.Limiter
	}
	return nil
}

func (m *Config) GetGlobal() *Global {
	if m != nil {
		return m.Global
	}
	return nil
}

func (m *Config) GetFence() *Fence {
	if m != nil {
		return m.Fence
	}
	return nil
}

func (m *Config) GetMetric() *Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *Config) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Config) GetGeneral() *General {
	if m != nil {
		return m.General
	}
	return nil
}

func (m *Config) GetBundle() *Bundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

func (m *Config) GetMode() Config_Mode {
	if m != nil {
		return m.Mode
	}
	return Config_Module
}

func (m *Config) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

// ConfigSource describes information about a configuration store inside a
// mesh. A single control plane instance can interact with one or more data
// sources.
type ConfigSource struct {
	// Address of the server implementing the Istio Mesh Configuration
	// protocol (MCP). Can be IP address or a fully qualified DNS name.
	// Use fs:/// to specify a file-based backend with absolute path to the directory.
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigSource) Reset()         { *m = ConfigSource{} }
func (m *ConfigSource) String() string { return proto.CompactTextString(m) }
func (*ConfigSource) ProtoMessage()    {}
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{14}
}
func (m *ConfigSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSource.Unmarshal(m, b)
}
func (m *ConfigSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSource.Marshal(b, m, deterministic)
}
func (m *ConfigSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSource.Merge(m, src)
}
func (m *ConfigSource) XXX_Size() int {
	return xxx_messageInfo_ConfigSource.Size(m)
}
func (m *ConfigSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSource proto.InternalMessageInfo

func (m *ConfigSource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClientGoTokenBucket struct {
	// QPS indicates the maximum QPS to the master from this client.
	Qps int32 `protobuf:"varint,1,opt,name=qps,proto3" json:"qps,omitempty"`
	// Maximum burst for throttle.
	Burst                int32    `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGoTokenBucket) Reset()         { *m = ClientGoTokenBucket{} }
func (m *ClientGoTokenBucket) String() string { return proto.CompactTextString(m) }
func (*ClientGoTokenBucket) ProtoMessage()    {}
func (*ClientGoTokenBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{15}
}
func (m *ClientGoTokenBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoTokenBucket.Unmarshal(m, b)
}
func (m *ClientGoTokenBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoTokenBucket.Marshal(b, m, deterministic)
}
func (m *ClientGoTokenBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoTokenBucket.Merge(m, src)
}
func (m *ClientGoTokenBucket) XXX_Size() int {
	return xxx_messageInfo_ClientGoTokenBucket.Size(m)
}
func (m *ClientGoTokenBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoTokenBucket.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoTokenBucket proto.InternalMessageInfo

func (m *ClientGoTokenBucket) GetQps() int32 {
	if m != nil {
		return m.Qps
	}
	return 0
}

func (m *ClientGoTokenBucket) GetBurst() int32 {
	if m != nil {
		return m.Burst
	}
	return 0
}

func init() {
	proto.RegisterEnum("slime.config.v1alpha1.Limiter_RateLimitBackend", Limiter_RateLimitBackend_name, Limiter_RateLimitBackend_value)
	proto.RegisterEnum("slime.config.v1alpha1.Prometheus_Source_Type", Prometheus_Source_Type_name, Prometheus_Source_Type_value)
	proto.RegisterEnum("slime.config.v1alpha1.Config_Mode", Config_Mode_name, Config_Mode_value)
	proto.RegisterType((*LocalSource)(nil), "slime.config.v1alpha1.LocalSource")
	proto.RegisterType((*RemoteSource)(nil), "slime.config.v1alpha1.RemoteSource")
	proto.RegisterType((*Plugin)(nil), "slime.config.v1alpha1.Plugin")
	proto.RegisterType((*Limiter)(nil), "slime.config.v1alpha1.Limiter")
	proto.RegisterType((*Global)(nil), "slime.config.v1alpha1.Global")
	proto.RegisterMapType((map[string]string)(nil), "slime.config.v1alpha1.Global.MiscEntry")
	proto.RegisterType((*Log)(nil), "slime.config.v1alpha1.Log")
	proto.RegisterType((*LogRotateConfig)(nil), "slime.config.v1alpha1.LogRotateConfig")
	proto.RegisterType((*Fence)(nil), "slime.config.v1alpha1.Fence")
	proto.RegisterType((*Prometheus_Source)(nil), "slime.config.v1alpha1.Prometheus_Source")
	proto.RegisterMapType((map[string]*Prometheus_Source_Handler)(nil), "slime.config.v1alpha1.Prometheus_Source.HandlersEntry")
	proto.RegisterType((*Prometheus_Source_Handler)(nil), "slime.config.v1alpha1.Prometheus_Source.Handler")
	proto.RegisterType((*K8S_Source)(nil), "slime.config.v1alpha1.K8S_Source")
	proto.RegisterType((*Metric)(nil), "slime.config.v1alpha1.Metric")
	proto.RegisterType((*General)(nil), "slime.config.v1alpha1.General")
	proto.RegisterType((*Bundle)(nil), "slime.config.v1alpha1.Bundle")
	proto.RegisterType((*Bundle_Item)(nil), "slime.config.v1alpha1.Bundle.Item")
	proto.RegisterType((*Config)(nil), "slime.config.v1alpha1.Config")
	proto.RegisterType((*ConfigSource)(nil), "slime.config.v1alpha1.ConfigSource")
	proto.RegisterType((*ClientGoTokenBucket)(nil), "slime.config.v1alpha1.ClientGoTokenBucket")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 1309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xe2, 0xbf, 0xf8, 0x38, 0x49, 0xdd, 0x2d, 0xb4, 0xc2, 0xb4, 0x25, 0xa8, 0x33, 0xc5,
	0x03, 0x54, 0xa6, 0xee, 0x50, 0x42, 0xa1, 0x17, 0x75, 0x7f, 0x92, 0x0e, 0x09, 0x93, 0x6e, 0x0a,
	0x17, 0x0c, 0x33, 0x1d, 0x59, 0x5e, 0xcb, 0x1a, 0xaf, 0xb4, 0xaa, 0x7e, 0x9c, 0x86, 0x17, 0xe0,
	0x9e, 0x2b, 0x5e, 0x80, 0x19, 0x5e, 0x87, 0x1b, 0x6e, 0x79, 0x00, 0xee, 0x78, 0x02, 0x66, 0xcf,
	0xae, 0x64, 0xe5, 0x47, 0xa1, 0xdc, 0xed, 0x39, 0xfb, 0x9d, 0x3d, 0x7f, 0xdf, 0x9e, 0x5d, 0x58,
	0x77, 0x45, 0x38, 0xf5, 0x3d, 0x3b, 0x8a, 0x45, 0x2a, 0xc8, 0xbb, 0x09, 0xf7, 0x03, 0x66, 0x6b,
	0xdd, 0xe2, 0xae, 0xc3, 0xa3, 0x99, 0x73, 0xb7, 0x77, 0xc7, 0xf3, 0xd3, 0x59, 0x36, 0xb6, 0x5d,
	0x11, 0x0c, 0x3c, 0xe1, 0x89, 0x01, 0xa2, 0xc7, 0xd9, 0x14, 0x25, 0x14, 0x70, 0xa5, 0x4e, 0xe9,
	0xdd, 0xf4, 0x84, 0xf0, 0x38, 0x5b, 0xa2, 0x26, 0x59, 0xec, 0xa4, 0xbe, 0x08, 0xd5, 0xbe, 0x75,
	0x0b, 0x3a, 0x7b, 0xc2, 0x75, 0xf8, 0xa1, 0xc8, 0x62, 0x97, 0x91, 0x77, 0xa0, 0x11, 0x88, 0x2c,
	0x4c, 0x4d, 0x63, 0xcb, 0xe8, 0xb7, 0xa9, 0x12, 0xac, 0x3e, 0xac, 0x53, 0x16, 0x88, 0x94, 0x69,
	0x94, 0x09, 0x2d, 0x67, 0x32, 0x89, 0x59, 0x92, 0x68, 0x5c, 0x2e, 0x5a, 0xbf, 0x18, 0xd0, 0x3c,
	0xe0, 0x99, 0xe7, 0x87, 0xe4, 0x01, 0x34, 0xb8, 0x3c, 0xd9, 0x5c, 0xdd, 0x32, 0xfa, 0x9d, 0xa1,
	0x65, 0x9f, 0x9b, 0x8f, 0x5d, 0xf2, 0xbe, 0xbb, 0x42, 0x95, 0x09, 0x79, 0x08, 0xcd, 0x18, 0x1d,
	0x9a, 0x35, 0x34, 0xbe, 0x55, 0x61, 0x5c, 0x8e, 0x6a, 0x77, 0x85, 0x6a, 0xa3, 0xd1, 0x06, 0x74,
	0x8e, 0x9c, 0x24, 0x78, 0x95, 0xe0, 0x86, 0xf5, 0xf7, 0x2a, 0xb4, 0xf6, 0xfc, 0xc0, 0x4f, 0x59,
	0x4c, 0x9e, 0x43, 0x6b, 0xec, 0xb8, 0x73, 0x16, 0x4e, 0xf0, 0xe8, 0xcd, 0xe1, 0xa0, 0x2a, 0x2e,
	0x65, 0x60, 0x53, 0x27, 0x65, 0xb8, 0x1e, 0x29, 0x33, 0x9a, 0xdb, 0x93, 0x2f, 0xa1, 0x15, 0xb3,
	0x69, 0xcc, 0x92, 0x99, 0x59, 0xc7, 0x28, 0xdf, 0xb3, 0x55, 0xb1, 0xed, 0xbc, 0xd8, 0xf6, 0x13,
	0x5d, 0xec, 0x51, 0xfd, 0xd7, 0xbf, 0x3e, 0x30, 0x68, 0x8e, 0x27, 0xf7, 0xe1, 0xea, 0xc4, 0x4f,
	0x9c, 0x31, 0x67, 0x3b, 0x5c, 0x8c, 0x1d, 0x5e, 0x38, 0x31, 0x1b, 0x5b, 0x46, 0x7f, 0x8d, 0x56,
	0xec, 0x92, 0x3e, 0x5c, 0xd2, 0x3b, 0x8f, 0x26, 0x4e, 0x94, 0xfa, 0x0b, 0x66, 0x36, 0xd1, 0xe0,
	0xb4, 0x9a, 0xd8, 0x40, 0x58, 0x28, 0x35, 0x87, 0x2c, 0x5e, 0xf8, 0x2e, 0x7b, 0x1a, 0xa6, 0xf1,
	0xb1, 0xd9, 0x42, 0xf0, 0x39, 0x3b, 0xd6, 0x2e, 0x74, 0x4f, 0x67, 0x4a, 0xde, 0x87, 0x6b, 0x21,
	0x4b, 0x9f, 0x3a, 0x09, 0xc3, 0x26, 0x3d, 0xe3, 0xe2, 0xe8, 0xb1, 0x08, 0xd3, 0x58, 0xf0, 0xee,
	0x0a, 0xb9, 0x06, 0x57, 0x58, 0xb8, 0x10, 0xc7, 0xb8, 0x55, 0x98, 0x76, 0x0d, 0xeb, 0xcf, 0x06,
	0x34, 0x55, 0xdc, 0x92, 0x27, 0x89, 0x72, 0x92, 0xf3, 0x44, 0x8b, 0xc4, 0x82, 0xf5, 0x20, 0xe3,
	0xa9, 0xef, 0xf2, 0x2c, 0x49, 0x59, 0x8c, 0x1c, 0x69, 0xd3, 0x13, 0x3a, 0x72, 0x1b, 0x36, 0xfd,
	0x24, 0xf5, 0xc5, 0xb7, 0x4e, 0xc0, 0x92, 0xc8, 0x71, 0x15, 0x19, 0xda, 0xf4, 0x94, 0x56, 0xe2,
	0xb0, 0x85, 0x4b, 0x5c, 0x5d, 0xe1, 0x4e, 0x6a, 0xc9, 0xa7, 0x50, 0xe3, 0xc2, 0xc3, 0x0a, 0x77,
	0x86, 0xbd, 0x4a, 0x3a, 0x7a, 0x54, 0xc2, 0xc8, 0x57, 0x50, 0x0f, 0xfc, 0xc4, 0x35, 0x9b, 0x5b,
	0xb5, 0x7e, 0x67, 0xf8, 0x51, 0x05, 0x5c, 0x25, 0x6a, 0xef, 0xfb, 0x89, 0x8b, 0x75, 0xa4, 0x68,
	0x44, 0x7a, 0xb0, 0x86, 0x41, 0x52, 0xb6, 0xc0, 0x9a, 0xb7, 0x69, 0x21, 0x93, 0xeb, 0xd0, 0x4e,
	0xd2, 0xd8, 0x77, 0x53, 0xb9, 0xb9, 0x86, 0x0d, 0x59, 0x2a, 0xc8, 0x73, 0xd8, 0x50, 0x3e, 0x14,
	0xa9, 0x13, 0xb3, 0x8d, 0xfe, 0xab, 0x2e, 0xc0, 0xe3, 0x12, 0x96, 0x9e, 0xb4, 0x94, 0x8e, 0x02,
	0x47, 0x56, 0xf2, 0xbb, 0x98, 0x9b, 0x80, 0x51, 0x2c, 0x15, 0x72, 0x57, 0xc1, 0x65, 0x18, 0x1d,
	0xb5, 0x5b, 0x28, 0xc8, 0x8f, 0x70, 0xc5, 0xe5, 0x3e, 0x0b, 0xd3, 0x1d, 0xf1, 0x52, 0xcc, 0x59,
	0x38, 0xca, 0xdc, 0x39, 0x4b, 0xcd, 0x75, 0xac, 0xdd, 0xc7, 0x55, 0xc1, 0x9c, 0xb5, 0xa0, 0xe7,
	0x1d, 0x23, 0x69, 0x9c, 0x30, 0x3e, 0xa5, 0x4c, 0x5d, 0x50, 0x19, 0xc1, 0x06, 0x46, 0x70, 0x5a,
	0x4d, 0x5e, 0xc0, 0x65, 0x2c, 0x5c, 0x39, 0x4f, 0x73, 0xf3, 0xc2, 0x99, 0x70, 0xa2, 0x24, 0x67,
	0xad, 0x7b, 0x5f, 0x40, 0xbb, 0x68, 0x17, 0xe9, 0x42, 0x6d, 0xce, 0x8e, 0x35, 0x3b, 0xe5, 0x52,
	0x4e, 0xc0, 0x85, 0xc3, 0x33, 0xa6, 0x29, 0xa9, 0x84, 0x07, 0xab, 0xdb, 0x86, 0xf5, 0x87, 0x01,
	0xb5, 0x3d, 0xe1, 0xc9, 0xe6, 0x72, 0xe1, 0xed, 0xb1, 0x05, 0xe3, 0xda, 0xb0, 0x90, 0x65, 0x55,
	0xe7, 0xc5, 0xa6, 0x3c, 0xa1, 0x41, 0x97, 0x0a, 0xb9, 0xcb, 0x85, 0x47, 0x45, 0xea, 0xe8, 0xc9,
	0xb6, 0x46, 0x97, 0x0a, 0x72, 0x00, 0x97, 0x0a, 0x41, 0x45, 0xac, 0xe7, 0xca, 0xed, 0x0b, 0xb8,
	0x5a, 0x42, 0xd3, 0xd3, 0xe6, 0x64, 0x0b, 0x3a, 0xea, 0xaa, 0xbf, 0xc8, 0xe4, 0x2c, 0x55, 0xb3,
	0xa5, 0xac, 0xb2, 0x7e, 0x33, 0xe0, 0xd2, 0xa9, 0x63, 0x64, 0x7e, 0x53, 0x9f, 0xb3, 0x03, 0x27,
	0x9d, 0xe5, 0xf9, 0xe5, 0xb2, 0xe2, 0xd4, 0x9b, 0x43, 0xff, 0x27, 0xb6, 0x3f, 0xca, 0xf3, 0x2b,
	0x14, 0xe4, 0x26, 0x40, 0xe0, 0xbc, 0x91, 0xe3, 0x23, 0x8b, 0x12, 0x4c, 0xb0, 0x41, 0x4b, 0x1a,
	0x6d, 0xfd, 0xc8, 0x63, 0x4f, 0x9c, 0x63, 0xcc, 0x4d, 0x59, 0x2b, 0x85, 0xf4, 0xeb, 0x8a, 0x20,
	0xc2, 0x67, 0x45, 0x85, 0x5a, 0xc8, 0xd6, 0x27, 0xd0, 0x78, 0xc6, 0x42, 0x35, 0x38, 0x8e, 0x44,
	0x1c, 0xcc, 0x04, 0x67, 0x07, 0x22, 0x4e, 0xcd, 0xd5, 0xad, 0x9a, 0x1c, 0x1c, 0x65, 0x9d, 0xf5,
	0xcf, 0x2a, 0x5c, 0x3e, 0x88, 0x45, 0xc0, 0xd2, 0x19, 0xcb, 0x92, 0x57, 0xff, 0xf5, 0x68, 0x11,
	0x0a, 0x6b, 0x33, 0x27, 0x9c, 0x70, 0x16, 0x27, 0x78, 0x5e, 0x67, 0x78, 0xbf, 0xa2, 0xe2, 0x67,
	0x4e, 0xb5, 0x77, 0xb5, 0xa1, 0xba, 0xfd, 0xc5, 0x39, 0xbd, 0x31, 0xb4, 0xf4, 0x96, 0x64, 0xd4,
	0xeb, 0x8c, 0xc5, 0x39, 0xcb, 0x94, 0x40, 0x1e, 0x41, 0x3d, 0x3d, 0x8e, 0x14, 0xcd, 0x36, 0x87,
	0x77, 0xde, 0xda, 0xe1, 0xcb, 0xe3, 0x88, 0x51, 0x34, 0xed, 0x05, 0xb0, 0x71, 0xc2, 0xfd, 0x39,
	0x6c, 0x7e, 0x56, 0x66, 0x73, 0x67, 0xf8, 0xd9, 0xff, 0xcd, 0xab, 0xcc, 0xff, 0xeb, 0x50, 0x97,
	0xce, 0x49, 0x1b, 0x1a, 0xdf, 0x4b, 0x65, 0x77, 0x45, 0x2e, 0x77, 0x62, 0x91, 0x45, 0x5d, 0xc3,
	0xea, 0x03, 0x7c, 0xb3, 0x7d, 0x98, 0x17, 0xbb, 0x57, 0x2a, 0xa9, 0x81, 0x2d, 0x2a, 0x64, 0xeb,
	0x67, 0x03, 0x9a, 0xfb, 0x4c, 0x4e, 0x3c, 0xb2, 0x0b, 0x10, 0x15, 0xae, 0x31, 0xee, 0xce, 0xb0,
	0xff, 0xb6, 0x31, 0xd2, 0x92, 0x2d, 0xb9, 0x07, 0xb5, 0xf9, 0x76, 0xa2, 0xd3, 0xfc, 0xb0, 0xe2,
	0x88, 0x65, 0x80, 0x54, 0xa2, 0xad, 0x36, 0xb4, 0x76, 0x58, 0xc8, 0x62, 0x87, 0x5b, 0x0b, 0x68,
	0x8e, 0x32, 0x19, 0x20, 0xf9, 0x1a, 0x5a, 0x81, 0x98, 0x64, 0x9c, 0xa9, 0xc8, 0xab, 0x7f, 0x2e,
	0x0a, 0x6f, 0x3f, 0x4f, 0x59, 0x40, 0x73, 0x93, 0x9e, 0x0d, 0x75, 0xa9, 0x20, 0x04, 0xea, 0xa1,
	0x13, 0xe4, 0xef, 0x1e, 0xae, 0xa5, 0x6e, 0xee, 0x87, 0x13, 0x3d, 0x59, 0x70, 0x6d, 0xfd, 0x5e,
	0x87, 0xa6, 0xbe, 0x77, 0x9f, 0x43, 0x33, 0xc2, 0xaf, 0x93, 0x2e, 0xc4, 0x8d, 0xaa, 0x42, 0x20,
	0x88, 0x6a, 0x30, 0xd9, 0x86, 0x16, 0x57, 0x7f, 0x15, 0x9d, 0xfd, 0xcd, 0x8b, 0x7f, 0x34, 0x34,
	0x87, 0x4b, 0x87, 0x1e, 0xbe, 0x5f, 0xfa, 0x97, 0x75, 0xe3, 0xc2, 0x47, 0x8e, 0x6a, 0x30, 0x19,
	0x42, 0x63, 0x2a, 0xef, 0xa2, 0x9e, 0x4e, 0xd7, 0x2b, 0xac, 0xf0, 0xbe, 0x52, 0x05, 0x95, 0xae,
	0x02, 0x6c, 0x39, 0xfe, 0x57, 0xaa, 0x5d, 0x29, 0x5e, 0x50, 0x0d, 0x2e, 0xaa, 0xd8, 0x28, 0x55,
	0xf1, 0x2a, 0x34, 0xd5, 0x04, 0xd3, 0xbf, 0x19, 0x2d, 0xc9, 0x3a, 0x78, 0xaa, 0x99, 0xf8, 0xaa,
	0x56, 0xd7, 0x41, 0xb7, 0x9c, 0xe6, 0x70, 0x19, 0xdc, 0x18, 0x7b, 0x69, 0xb6, 0x2f, 0x0c, 0x4e,
	0x35, 0x9c, 0x6a, 0x30, 0xb9, 0x0f, 0xf5, 0x40, 0x4c, 0x18, 0x3e, 0xad, 0x9b, 0x95, 0x2c, 0x51,
	0xcd, 0xb5, 0xf7, 0xc5, 0x84, 0x51, 0xc4, 0x17, 0x34, 0xe8, 0x94, 0x68, 0x60, 0x41, 0x5d, 0x22,
	0x08, 0x40, 0x73, 0x1f, 0x99, 0xd4, 0x5d, 0x21, 0x9b, 0x00, 0xca, 0xa3, 0x24, 0x14, 0xde, 0xb0,
	0xf5, 0xf2, 0x43, 0x76, 0xc1, 0x2f, 0xfc, 0x21, 0x5c, 0x39, 0xe7, 0x2d, 0x96, 0xe3, 0xe1, 0x75,
	0xa4, 0xc0, 0x0d, 0x2a, 0x97, 0x72, 0x34, 0x8d, 0xb3, 0x38, 0x49, 0xf5, 0x28, 0x57, 0xc2, 0x68,
	0xf0, 0xc3, 0x1d, 0x95, 0x8b, 0x2f, 0x06, 0xb8, 0x18, 0x4c, 0x63, 0x27, 0x60, 0x47, 0x22, 0x9e,
	0x0f, 0x9c, 0xc8, 0x4f, 0x06, 0x2a, 0xc7, 0x41, 0x9e, 0xe3, 0xb8, 0x89, 0x1f, 0xde, 0x7b, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x05, 0x66, 0xeb, 0xc1, 0x0c, 0x00, 0x00,
}
