// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slime_boot.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SlimeBootStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlimeBootStatus) Reset()         { *m = SlimeBootStatus{} }
func (m *SlimeBootStatus) String() string { return proto.CompactTextString(m) }
func (*SlimeBootStatus) ProtoMessage()    {}
func (*SlimeBootStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{0}
}
func (m *SlimeBootStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlimeBootStatus.Unmarshal(m, b)
}
func (m *SlimeBootStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlimeBootStatus.Marshal(b, m, deterministic)
}
func (m *SlimeBootStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlimeBootStatus.Merge(m, src)
}
func (m *SlimeBootStatus) XXX_Size() int {
	return xxx_messageInfo_SlimeBootStatus.Size(m)
}
func (m *SlimeBootStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SlimeBootStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SlimeBootStatus proto.InternalMessageInfo

type SlimeBootSpec struct {
	Module               []*Config  `protobuf:"bytes,1,rep,name=module,proto3" json:"module,omitempty"`
	Component            *Component `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SlimeBootSpec) Reset()         { *m = SlimeBootSpec{} }
func (m *SlimeBootSpec) String() string { return proto.CompactTextString(m) }
func (*SlimeBootSpec) ProtoMessage()    {}
func (*SlimeBootSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{1}
}
func (m *SlimeBootSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlimeBootSpec.Unmarshal(m, b)
}
func (m *SlimeBootSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlimeBootSpec.Marshal(b, m, deterministic)
}
func (m *SlimeBootSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlimeBootSpec.Merge(m, src)
}
func (m *SlimeBootSpec) XXX_Size() int {
	return xxx_messageInfo_SlimeBootSpec.Size(m)
}
func (m *SlimeBootSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SlimeBootSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SlimeBootSpec proto.InternalMessageInfo

func (m *SlimeBootSpec) GetModule() []*Config {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *SlimeBootSpec) GetComponent() *Component {
	if m != nil {
		return m.Component
	}
	return nil
}

type Component struct {
	GlobalSidecarNamespace []string `protobuf:"bytes,1,rep,name=globalSidecarNamespace,proto3" json:"globalSidecarNamespace,omitempty"`
	ReportServer           bool     `protobuf:"varint,2,opt,name=reportServer,proto3" json:"reportServer,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf8433223eb5dea, []int{2}
}
func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetGlobalSidecarNamespace() []string {
	if m != nil {
		return m.GlobalSidecarNamespace
	}
	return nil
}

func (m *Component) GetReportServer() bool {
	if m != nil {
		return m.ReportServer
	}
	return false
}

func init() {
	proto.RegisterType((*SlimeBootStatus)(nil), "slime.config.v1alpha1.SlimeBootStatus")
	proto.RegisterType((*SlimeBootSpec)(nil), "slime.config.v1alpha1.SlimeBootSpec")
	proto.RegisterType((*Component)(nil), "slime.config.v1alpha1.Component")
}

func init() { proto.RegisterFile("slime_boot.proto", fileDescriptor_6bf8433223eb5dea) }

var fileDescriptor_6bf8433223eb5dea = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0xa9, 0xc2, 0xb0, 0xd9, 0x44, 0x0d, 0x28, 0x43, 0x10, 0x4a, 0x4f, 0xbb, 0x98, 0xb0,
	0x89, 0x1e, 0x3d, 0xcc, 0xbb, 0x87, 0xf6, 0xe6, 0x45, 0x5e, 0xb3, 0xb7, 0x1a, 0x4c, 0xfa, 0x42,
	0x92, 0xcd, 0x7f, 0xe0, 0xef, 0x16, 0xd3, 0xea, 0x10, 0xec, 0x2d, 0xf9, 0xf2, 0xbd, 0xf0, 0xf1,
	0xd8, 0x79, 0x30, 0xda, 0xe2, 0x6b, 0x43, 0x14, 0x85, 0xf3, 0x14, 0x89, 0x5f, 0x26, 0x22, 0x14,
	0x75, 0x5b, 0xdd, 0x8a, 0xfd, 0x12, 0x8c, 0x7b, 0x83, 0xe5, 0xf5, 0x6c, 0x00, 0x49, 0x2a, 0x2f,
	0xd8, 0x59, 0xfd, 0xad, 0xad, 0x89, 0x62, 0x1d, 0x21, 0xee, 0x42, 0xf9, 0x99, 0xb1, 0xd3, 0x03,
	0x73, 0xa8, 0xf8, 0x3d, 0x9b, 0x58, 0xda, 0xec, 0x0c, 0xce, 0xb3, 0xe2, 0x78, 0x31, 0x5d, 0xdd,
	0x88, 0x7f, 0xbf, 0x16, 0x4f, 0xe9, 0x5e, 0x0d, 0x32, 0x7f, 0x64, 0xb9, 0x22, 0xeb, 0xa8, 0xc3,
	0x2e, 0xce, 0x8f, 0x8a, 0x6c, 0x31, 0x5d, 0x15, 0xa3, 0x93, 0x83, 0x57, 0x1d, 0x46, 0xca, 0x96,
	0xe5, 0xbf, 0x9c, 0x3f, 0xb0, 0xab, 0xd6, 0x50, 0x03, 0xa6, 0xd6, 0x1b, 0x54, 0xe0, 0x9f, 0xc1,
	0x62, 0x70, 0xa0, 0xfa, 0xa6, 0xbc, 0x1a, 0x79, 0xe5, 0x25, 0x9b, 0x79, 0x74, 0xe4, 0x63, 0x8d,
	0x7e, 0x8f, 0x3e, 0x75, 0x9c, 0x54, 0x7f, 0xd8, 0x5a, 0xbe, 0xdc, 0xf6, 0x59, 0x9a, 0x64, 0x3a,
	0xc8, 0xad, 0x07, 0x8b, 0x1f, 0xe4, 0xdf, 0x25, 0x38, 0x1d, 0x64, 0x9f, 0x2b, 0x7f, 0x72, 0x9b,
	0x49, 0x5a, 0xde, 0xdd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x67, 0x99, 0xf9, 0x75, 0x01,
	0x00, 0x00,
}
